{extends file='main.phtml'}
{block name=rtitle}充装管理{/block}
{block name=body}
<div class="contRList">
    <form name="form" method="POST" action="/filling/addrecords">
        <!--div class="rqLine clearfix">
            <div class="rqOption clearfix rqRadio">
                <label class="fl">类型：</label>
                <div class="myradio fl">
                    <div class="radiobox clearfix">
                        <input type="radio" name="type" value="0" checked="checked" /> 充装
                        <input type="radio" name="type" value="1" /> 配送
                    </div>
                </div>
            </div>
        </div-->
        <input type="hidden" name='type' value="0" />
        <div class="rqLine clearfix bottlerecords">
            <div class="rqOption fl">
                <label class="fl">瓶类型：</label>
                <div class="selectBox fl" style="width:150px;">
                    <select name="btype[]" class="selectmenu">
                        {foreach $btypes as $k=>$v}
                        <option value="{$k}">{$v}</option>
                        {/foreach}
                    </select>
                </div>
            </div>
            <div class="rqOption fl">
                <label class="fl">数量：</label>
                <div class="inputBox fl placeholder">
                    <input type="text" name="bnum[]" value="{$num}" style="width:180px;">
                </div>
            </div>
            <div class="rqOption fl"><a href="javascript:;" class="add">+</a></div>
        </div>
        <div class="rqLine clearfix pd" id="product">
            <div class="rqOption fl">
                <label class="fl">总数量：</label>
                <div class="inputBox fl placeholder">
                    <input type="text" name="num" value="{$num}" style="width:180px;">
                </div>
            </div>
        </div>
        <div class="rqLine">
            <div class="rqOption clearfix">
                <label class="fl"></label>
                <div class="fl">
                    <div class="rqLine">
                        <div class="rqOption fl">
                            <a href="javascript:if(confirm('提交后不可更改，确定提交？')){ document.form.submit(); }" class="blueBtn">保存</a>
                        </div>
                        <div class="rqOption fl">
                            <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" name="id" value="{$kid}">
        <input type="hidden" name="filling_sn" value="{$filling_sn}" />
    </form>
</div>
<script type="text/javascript">
    $(function () {
        $('.add').live('click', function () {
            var pt = $(this).parents("div .bottlerecords"), bottle = pt.clone();
            bottle.find('select').show().removeAttr('id').selectmenu().next().next().remove();
            bottle.find('select').selectmenu('refresh').next().attr('style',pt.find('.ui-selectmenu-button').attr('style'));
            bottle.find('div:last>a').removeClass('add').addClass('del').html('-');
            bottle.find('input:first').val('');
            if (pt.attr('id') == 'product') {
                $('#comment').before(bottle);
            } else {
                $('#product').before(bottle);
            }
        });
        $('.del').live('click', function () {
            $(this).parents('.rqLine').remove();
        });
    });
</script>
{/block}