{extends file='ztemp/main.phtml'}
{block name=title}门店确认入库单{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        门店确认入库单
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST">
            <div class="rqLine">
                <div class="rqOption fl clearfix">
                    <label class="fl">单号：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="confirme_no" id="confirme_no" value="{$param['confirme_no']}" style="width:128px;">
                    </div>
                </div>
                {if isset($is_show_shop) && !empty($is_show_shop)}
                <div class="rqOption fl"><input type="hidden" name="shop_id" value="{$is_show_shop}" /></div>
                {else}
                <div class="rqOption fl">
                    <label class="fl">门店：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="shop_id" class="selectmenu" style="width:140px;">
                                <option selected="selected" value='0'>请选择门店</option>
                                {if $shopObject neq ''}
                                {foreach $shopObject as $value}
                                {if $param['shop_id'] eq $value['shop_id']}
                                <option value="{$value['shop_id']}" selected="selected">{$value['shop_name']}</option>
                                {else}
                                <option value="{$value['shop_id']}">{$value['shop_name']}</option>
                                {/if}
                                {/foreach}
                                {/if}
                            </select>
                        </div>
                    </div>
                </div>
                {/if}
                <div class="rqOption fl">
                    <label class="fl">状态：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="status" class="selectmenu"  style="width:104px;">
                                <option value="">选择状态</option>
                                {if $param['status'] eq 1}
                                <option value="1" selected="selected">已处理</option>
                                <option value="2">未处理</option>
                                {else if $param['status'] eq 2}
                                <option value="1">已处理</option>
                                <option value="2" selected="selected">未处理</option>
                                {else}
                                <option value="1">已处理</option>
                                <option value="2">未处理</option>
                                {/if}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">出库时间：</label>
                    <div class="riliInputBox fl">
                        <div class="riliInput fl">
                            <input type="text" style="width:148px;" id="time_start" name="time_start" id="time_start" value="{$param['time_start']}">
                        </div>
                        <span class="fl">至</span>
                        <div class="riliInput fl">
                            <input type="text" id="time_end" name="time_end" id="time_end" style="width:148px;" value="{$param['time_end']}">
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                    <input type="submit" name="submit" class="blueBtn" value="搜索" />
                </div>
            </div>
        </form>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>单号</th>
                        <th>车牌号</th>
                        <th>押运员</th>
                        <th>配送内容</th>
                        <th>门店</th>
                        <th>出库时间</th>
                        <th>确认状态</th>
                    </tr>
                </thead>
                <tbody>
                    {if count($ext['list']) neq 0}
                    {foreach $ext['list'] as $value}
                    <tr>
                        <td>{$value['confirme_no']}</td>
                        <td>{$value['license_plate']}</td>
                        <td>{$value['guards']}</td>
                        <td class="tableBtn">
                            <a href="/filling/confirmeinfo?sno={$value['confirme_no']}&shop_id={$value['shop_id']}" target="_blank">配送详情</a>
                        </td>
                        <td>{$shopObject[$value['shop_id']]['shop_name']}</td>
                        <td>{$value['time']}</td>
                        {if $value['status'] eq 0}
                        <td class="redColor qrrk" cno="{$value['confirme_no']}" shop_id="{$value['shop_id']}">待确认</td>
                        {else}
                        <td>已确认|<a href="/filling/confirmebottle?sn={$value['confirme_no']}&shop_id={$value['shop_id']}" target="_blank">钢瓶详情</a></td>
                        {/if}
                    </tr>
                    {/foreach}
                    {else}
                    <tr><td colspan="8">暂时还没有门店入库确认单</td></tr>
                    {/if}
                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$page}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
            <input type="hidden" class="paramlist" value="{$getparamlist}" />
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/mendianrukudan.js"></script>{/block}