{extends file='ztemp/main.phtml'}
{block name=title}门店确认单详情{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        配送出库单详情
        <span></span>
        <p>出库时间：{$time}</p>
    </div>
    <div class="contRList">
        <div class="path">
            <a href="/filling/confirme">门店确认单列表</a>&nbsp;
            <i></i>&nbsp;
            <a href="javascript:void(0);" class="active">门店确认单详情</a>
        </div>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>配送对象</th>
                        <th>商品类别</th>
                        <th>商品规格</th>
                        <th>数量</th>
                        <th>金额</th>
                        <th>合计</th>
                    </tr>
                </thead>
                <tbody>
                    {if $returnData neq ''}
                    {foreach $returnData as $key => $val}
                    <tr>
                        <td>{$val['shop_name']}</td>
                        <td>{($val['ftype']==1)? '液化气': $val['name']}</td>
                        <td>{$val['fname']}</td>
                        <td>{$val['num']}</td>
                        <td>{$val['total']}</td>
                        {if $key eq 0}
                        <td rowspan="{$count}">{$totalMoney}</td>
                        {/if}
                    </tr>
                    {/foreach}
                    {/if}
                </tbody>
            </table>
        </div>
        {if $status eq 0}
        <div  class="rqLine">
            <div class="rqOption fr">
                <input type="hidden" id="sno" value="{$sno}" />
                <input type="hidden" id="tmoney" value="{$totalMoney}" />
                <a href="javascript:;" class="blueBtn" id="confirmbtn">确认入库</a>
            </div>
        </div>
        {/if}
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/mendianrukudan.js"></script>{/block}