{extends file='ztemp/main.phtml'}
{block name=title}钢瓶初始化记录{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        钢瓶初始化记录
        <span></span>
        <a href="javascript:;" class="blueBtn10" id="tbpda">手动钢瓶初始化记录</a>
    </div>
    <div class="contRList">
        <form name="form" method="POST">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">钢印号：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="number" id="number" value="{$param['number']}" style="width:148px;">
                    </div>
                </div>
                <div class="rqOption fl">
                    <label class="fl">芯片号：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="xinpian" id="xinpian" value="{$param['xinpian']}" style="width:148px;">
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">规格：</label>
                    <div class="selectBox fl" style="width:170px;">
                        <div class="mySelect">
                            <select name="type" id="type" class="selectmenu">
                                <option selected="selected" value="">全部</option>
                                {foreach $btypes as $bKey => $bVal}
                                {if $param['type'] eq $bKey}
                                <option value="{$bKey}" selected="selected">{$bVal}</option>
                                {else}
                                <option value="{$bKey}">{$bVal}</option>
                                {/if}
                                {/foreach}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <label class="fl">生产厂家：</label>
                    <div class="selectBox fl" style="width:170px;">
                        <div class="mySelect">
                            <select name="" class="selectmenu">
                                <option selected="selected">全部供应商</option>
                                {foreach $supplierData as $sKey => $sVal}
                                <option value="{$sVal['id']}">{$sVal['name']}</option>
                                {/foreach}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="rqOption fl mr0">
                    <div class="rqOption3 fl">
                        <label class="fl">发布时间：</label>
                        <div class="riliInputBox fl">
                            <div class="riliInput fl">
                                <input type="text" style="width:148px;" id="time_start" name="time_start" value="{$param['time_start']}">
                            </div>
                            <span class="fl">至</span>
                            <div class="riliInput fl">
                                <input type="text" id="time_end" style="width:148px;" name="time_end" value="{$param['time_end']}">
                            </div>
                        </div>
                    </div>
                    <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                    <input type="submit" name="submit" class="blueBtn" value="搜索" />
                </div>
            </div>
        </form>
        <div class="msgTitle clearfix mb20">
            <span class="fl">记录列表</span>
        </div>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>编号</th>
                        <th>钢印号</th>
                        <th>芯片号</th>
                        <th>条形码</th>
                        <th>规格</th>
                        <th>使用年限</th>
                        <th>强检周期</th>
                        <th>皮重</th>
                        <th>出厂日期</th>
                        <th>初始化日期</th>
                    </tr>
                </thead>
                <tbody>
                    {if $ext['list'] neq ''}
                    {foreach $ext['list'] as $key => $value}
                    <tr>
                        <td>{$key+1}</td>
                        <td>{$value['number']}</td>
                        <td>{$value['xinpian']}</td>
                        <td>
                            {$value['bar_code']}
                        </td>
                        <td>{$btypes[$value['type']]}</td>
                        <td>{$value['synx']}</td>
                        <td>{$value['qjzq']}</td>
                        <td>{$value['pz']}</td>
                        <td>{date('Y-m-d',substr($value['scrq'],0,-3))}</td>
                        <td>{date('Y-m-d H:i',$value['ctime'])}</td>
                    </tr>
                    {/foreach}
                    {else}
                    <tr><td colspan="9">暂时还没有钢瓶初始化记录</td></tr>
                    {/if}
                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$param['page']}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
            <input type="hidden" class="paramlist" value="{$getparamlist}" />
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/gangpingchushihuajilu.js"></script>{/block}