<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/style.css">
	<link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/base/jquery-ui.css">
	<script type="text/javascript" src="{$_PUBLIC}/js/jquery.min.js"></script>
	<script type="text/javascript" src="{$_PUBLIC}/js/jquery-ui.js"></script>
    </head>
    <body>
        <div class="wrap">
            {include file='staticpage_header.phtml'}
            <div class="content">
                {include file='staticpage_top.phtml'}
                <div class="contCent clearfix">
                    {include file='staticpage_right.phtml'}
                    <div class="contRight fr">
                        <div class="contRItem">
                            <div class="contRTitle">
                                门店管理
                                <span></span>
                            </div>
                            <div class="contRList">
                                <div class="rqLine clearfix">
                                    <div class="rqOption fl">
                                        <label class="fl">省：</label>
                                        <div class="selectBox fl" style="width:152px;">
                                            <div class="mySelect">
                                                <select name="" class="selectmenu" style="width:150px;">
                                                    <option>紧急订单</option>
                                                    <option>Slow</option>
                                                    <option selected="selected">Medium</option>
                                                    <option>Fast</option>
                                                    <option>Faster</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="rqOption fl">
                                        <label class="fl">市：</label>
                                        <div class="selectBox fl" style="width:152px;">
                                            <div class="mySelect">
                                                <select name="" class="selectmenu"  style="width:150px;">
                                                    <option>紧急订单</option>
                                                    <option>Slow</option>
                                                    <option selected="selected">Medium</option>
                                                    <option>Fast</option>
                                                    <option>Faster</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="rqOption fl">
                                        <label class="fl">区：</label>
                                        <div class="selectBox fl" style="width:152px;">
                                            <div class="mySelect">
                                                <select name="" class="selectmenu" style="width:150px;">
                                                    <option>紧急订单</option>
                                                    <option>Slow</option>
                                                    <option selected="selected">Medium</option>
                                                    <option>Fast</option>
                                                    <option>Faster</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="rqLine clearfix">
                                    <div class="rqOption fl">
                                        <label class="fl">街道：</label>
                                        <div class="selectBox fl" style="width:152px;">
                                            <div class="mySelect">
                                                <select name="" class="selectmenu" style="width:150px;">
                                                    <option>紧急订单</option>
                                                    <option>Slow</option>
                                                    <option selected="selected">Medium</option>
                                                    <option>Fast</option>
                                                    <option>Faster</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="rqOption fl">
                                        <label class="fl">等级：</label>
                                        <div class="selectBox fl" style="width:152px;">
                                            <div class="mySelect">
                                                <select name="" class="selectmenu" style="width:150px;">
                                                    <option selected="selected">中心店</option>
                                                    <option>Slow</option>
                                                    <option>Medium</option>
                                                    <option>Fast</option>
                                                    <option>Faster</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="rqOption fl">
                                        <a href="javascript:;" class="blueBtn">搜索</a>
                                    </div>
                                </div>
                                <div class="rq_table">
                                    <table>
                                        <thead>
                                            <tr>
                                                <th>编号</th>
                                                <th>门店名称</th>
                                                <th>等级</th>
                                                <th>操作</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>01</td>
                                                <td>建国门店</td>
                                                <td>中心店</td>
                                                <td>管理区域</td>
                                            </tr>
                                            <tr>
                                                <td>02</td>
                                                <td>建国门店</td>
                                                <td>社区店</td>
                                                <td>管理区域</td>
                                            </tr>
                                            <tr>
                                                <td>03</td>
                                                <td>建国门店</td>
                                                <td>卫星店</td>
                                                <td>管理区域</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {include file='staticpage_footer.phtml'}
        </div>
        <script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
    </body>
</html>