<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/style.css">
        <script type="text/javascript" src="{$_PUBLIC}/js/jquery.min.js"></script>
    </head>
    <body>
        <div class="wrap">
            {include file='staticpage_header.phtml'}
            <div class="content">
                {include file='staticpage_top.phtml'}
                <div class="contCent clearfix">
                    {include file='staticpage_right.phtml'}
                    <div class="contRight fr">
                        <div class="contRItem">
                            <div class="contRTitle">
                                销量状况
                                <span></span>
                            </div>
                            <div class="contRList">
                                <div class="rq_data">
                                    <ul class="clearfix">
                                        <li class="rq_down dataLi1">
                                            <p>总额</p>
                                            <span class="rq_num">￥<strong>1685.00</strong></span>
                                            <font>-8</font>
                                            <span class="percent">%</span>
                                            <i></i>
                                        </li>
                                        <li class="rq_up dataLi2">
                                            <p>总额</p>
                                            <span class="rq_num">￥<strong>1685.00</strong></span>
                                            <font>+8</font>
                                            <span class="percent">%</span>
                                            <i></i>
                                        </li>
                                        <li class="rq_up dataLi3">
                                            <p>总额</p>
                                            <span class="rq_num">￥<strong>1685.00</strong></span>
                                            <font>+8</font>
                                            <span class="percent">%</span>
                                            <i></i>
                                        </li>
                                    </ul>
                                </div>
                                <div class="rq_tab">
                                    <ul class="tabBtnbox clearfix rq_btnbox">
                                        <li class="tabBtn active">本周<span></span></li>
                                        <li class="tabBtn">本月<span></span></li>
                                        <li class="tabBtn">本季度<span></span></li>
                                        <li class="tabBtn">本年度<span></span></li>
                                    </ul>
                                    <ul class="tabItembox rq_itembox">
                                        <li class="tabItem" style="display:block;">
                                            <table>
                                                <thead>
                                                    <tr>
                                                        <th>门店类别</th>
                                                        <th>门店名称</th>
                                                        <th>主营收入<span>（元）</span></th>
                                                        <th>其他收入<span>（元）</span></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td>卫星店</td>
                                                        <td>建国门店</td>
                                                        <td>125412.00</td>
                                                        <td>125412.00</td>
                                                    </tr>
                                                    <tr>
                                                        <td>卫星店</td>
                                                        <td>建国门店</td>
                                                        <td>125412.00</td>
                                                        <td>125412.00</td>
                                                    </tr>
                                                    <tr>
                                                        <td>卫星店</td>
                                                        <td>建国门店</td>
                                                        <td>125412.00</td>
                                                        <td>125412.00</td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><strong>合计</strong></td>
                                                        <td>125412.00</td>
                                                        <td>125412.00</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {include file='staticpage_footer.phtml'}
        </div>
        <script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
    </body>
</html>