{extends file='main.phtml'}
{block name=rtitle}
出库管理
{/block}

{block name=body}
<table>
    <tr>
        <td>单据编号</td>
        <td>经办人</td>
        <td>经办站点</td>
        <td>经办时间</td>
        <td>生效人</td>
        <td>生效时间</td>
        <td>状态</td>  
        <td>操作</td>
    </tr>

    {foreach $list as $value}
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><a href="/outstock/edite?id={}">审核</a></td>
    </tr>
    {/foreach} 
</table>
{/block}
