{extends file='ztemp/main.phtml'}
{block name=title}退瓶管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=operate}
<div class="contRItem">
    <div class="contRTitle">
        退瓶管理
        <span></span>
    </div>
    <div class="contRList">
        <div class="tpData">
            <ul class="clearfix">
                <li>
                    <p>今日退瓶订单数量</p>
                    <span>{$jtTotal['total']}</span>
                </li>
                {if $dataTotal neq ''}
                {foreach $dataTotal as $tVal}
                <li>
                    <p>{$orderStatus[$tVal['status']]}退瓶订单数量</p>
                    <span>{$tVal['total']}</span>
                </li>
                {/foreach}
                {/if}
                <li  class="greenBg">
                    <p>累计退瓶订单数量</p>
                    <span>{$ext['count']}</span>
                </li>
            </ul>
        </div>
    </div>
</div>
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        退瓶列表
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST">
            <div class="rqLine clearfix">
                <div class="rqOption3 fl">
                    <label class="fl">客户姓名：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="username" value="{$param['username']}" style="width:120px;">
                    </div>
                </div>
                <div class="rqOption3 fl">
                    <label class="fl">客户电话：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="mobile" value="{$param['mobile']}" style="width:120px;">
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption3 fl">
                    <label class="fl">订单状态：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="status" class="selectmenu"  style="width:144px;">
                                <option value="">选择状态</option>
                                {if $orderStatus neq ''}
                                {foreach $orderStatus as $skey => $usVal}
                                {if $skey eq $param['status']}
                                <option value="{$skey}" selected="selected">{$usVal}</option>
                                {else}
                                <option value="{$skey}">{$usVal}</option>
                                {/if}
                                {/foreach}
                                {/if}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="rqOption3 fl">
                    <label class="fl">订单时间：</label>
                    <div class="riliInputBox fl">
                        <div class="riliInput fl">
                            <input type="text" name="time_start" style="width:152px;" id="time_start" value="{$param['time_start']}">
                        </div>
                        <span class="fl">至</span>
                        <div class="riliInput fl">
                            <input type="text" name="time_end" id="time_end" style="width:152px;" value="{$param['time_end']}">
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                    <input type="submit" name="submit" class="blueBtn" value="搜索" />
                </div>
            </div>
        </form>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>编号</th>
                        <th>下单时间</th>
                        <th>客户名称</th>
                        <th>客户电话</th>
                        <th>退瓶金额</th>
                        <th>隶属门店</th>
                        <th>类型</th>
                        <th>上门服务费</th>
                        <th>订单状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>

                    {if $ext['list'] neq ''}
                    {foreach $ext['list'] as $value}
                    <tr>
                        <td>{$value['depositsn']}</td>
                        <td>{date('m-d H:i',$value['time_created'])}</td>
                        <td class="tableBtn">{$value['username']}</td>
                        <td>{$value['mobile']}</td>
                        <td>
                            {$value['money']}
                        </td>
                        <td>{$shopObject[$value['shop_id']]['shop_name']}</td>
                        <td>{($value['type'] == 1) ? '退瓶' : '置换'}</td>
                        <td>{$value['doormoney']}</td>
                        <td>{(isset($orderStatus[$value['status']])) ? $orderStatus[$value['status']] : ''}</td>
                        <td>
                            {if $value['status'] neq 0}
                            <a href="/deposit/info?id={$value['id']}&shop_id={$value['shop_id']}">详情</a>
                            {/if}
                            {if $value['shipper_mobile'] eq ''}
                            <a href="/deposit/add?id={$value['id']}&shop_id={$value['shop_id']}" class="paifaBtn">派发</a>
                            {/if}
                        </td>
                    </tr>
                    {/foreach}
                    {else}
                    <tr><td colspan="8">暂时还没有数据</td></tr>
                    {/if}

                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$page}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
            <input type="hidden" class="paramlist" value="{$getparamlist}" />
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/tuipingManage.js"></script>{/block}