<div id="head" class="clearfix mb20">
    <div class="w1170">
        <h1 class="fl">
            <img src="/statics/newhome/images/logo.png" />
        </h1>
        <div class="nav fl">
            {assign var="smartyUrl" value=$smarty.server.REQUEST_URI}
            {if $smartyUrl eq '/index/home?temptype=new'}
            <a href="/organize/list?temptype=new">功能页</a>
            {else if $smartyUrl eq '/map/index' || $smartyUrl eq '/map/kehu' || $smartyUrl eq '/map/shop'}
            <a href="/map/index">送气工位置</a>
            <a href="/map/shop">门店地址</a>
            <a href="/map/kehu">客户标注</a>
            <a href="/organize/list?temptype=new">功能页</a>
            {else}
            <a href="javascript:;" class="active">运营简报</a>
            <a href="javascript:;">运营管理</a>
            <a href="javascript:;">销售</a>
            <a href="javascript:;">财务</a>
            <a href="javascript:;">生产</a>
            <a href="javascript:;">设置</a>
            {/if}
        </div>
        <div class="fr user"> 
            {if $smarty.session.userinfo neq ''}
            <a href="/my/home/index">{$smarty.session.userinfo.username}</a>
            <span>|</span>
            <a href="/my/passport/logout">退出</a>
            {else}
            <a href="/index/userlogin">登陆</a>
            {/if}
        </div>
    </div>
</div>