<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="renderer" content="webkit">
        <title>{block name=title}瑞气科技管理系统{/block}</title>
        {block name=head}{/block}
    </head>
    <body>
        <div class="wrap">
            <!-- 头部 -->
            {include file='znewtemp/header.phtml'}
            <!-- 中间内容 -->
            {block name=body}{/block}
            <!-- 底部 -->
            {include file='znewtemp/footer.phtml'}
        </div>
        {block name=fjs}{/block}
    </body>
</html>