<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="renderer" content="webkit" />
        <title>{block name=title}瑞气科技管理系统{/block}</title>
        {block name=head}{/block}
    </head>
    <body>
        <div class="wrap">
            <!-- 头部 -->
            {include file='znewtemp/header.phtml'}
            <!-- 中间内容 -->
            <div id="content">
                <!-- 列表 -->
                <div class="w1170 clearfix">
                    <!-- 左侧导航 -->
                    {include file='znewtemp/left.phtml'}
                    <!-- 右侧 -->
                    {block name=body}{/block}
                </div>
            </div>
            <!-- 底部 -->
            {include file='znewtemp/footer.phtml'}
        </div>
        {block name=fjs}{/block}
    </body>
</html>