{extends file='main.phtml'}
{block name=rtitle}燃气类型{/block}
{block name=operate}<a href="/gas/add">添加燃气类型</a>{/block}

{block name=body}
<div class="orderList contRList">
    <table>
        <tr>
            <td>编号</td>
            <td>类型</td>
            <td>备注</td>
            <td>操作</td>
        </tr>

        {foreach $list as $value}
        <tr>
            <td>{$value['gassn']}</td>
            <td>{$value['gas_name']}</td>
            <td>{$value['comment']}</td>
            <td>
                <a href="/gas/edite?id={$value['gid']}">修改</a>|
                <a href="/gas/del?id={$value['gid']}">删除</a>
            </td>
        </tr>
        {/foreach} 
    </table>
    <div class="table-pages pageNav clearfix" id="pageNav"></div>
</div>
<script type="text/javascript">
    var page = {$page};
    var totalPage = {$count};
</script>
<script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
{/block}