<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0"/>
	<title>账户绑定</title>
	<link rel="stylesheet" href="/statics/css/base.css"/>
	<link rel="stylesheet" href="/statics/css/style.css"/>
	<script src="/statics/js/jquery-1.8.3.min.js"></script>
	<script src="/statics/js/main.js"></script>
	<script type="text/javascript" src="/statics/js/Vue.min.js"></script>
	<script type="text/javascript" src="/statics/js/vue-resource.min.js"></script>
	{include '../header.phtml'}
</head>
<body id="Vbody">
	<div class="tel">
		<span>手机号</span><input id="phone" type="tel" placeholder="请输入手机号" maxlength="11">
	</div>
	<div class="code">
		<input id="vcode" type="number" placeholder="请输入验证码"><span>获取验证码</span>
	</div>
	<div v-on:click="bind" class="finish">完成</div>
<script type="text/javascript">

new Vue({
	el: '#Vbody',
	data:{
		
	},
	ready: function() {
		//this.$set('currtime',Date.parse(new Date()));
		//this.getPromotion();
	},
	methods: {
		//获取订单
		bind:function(){
			var phone = $('#phone').val();
			var vcode = $("#vcode").val();
			var openid = GetQueryString('openid');
			var fromurl = GetQueryString('fromurl');
			var params = {
					phone:phone,
					vcode:vcode,
					openid:openid,
					fromurl:fromurl
			};
			$.ajax({
				  type: 'GET',
				  url: '/wx/ucenter/bind',
				  data: params,
				  cache:false,  
				  dataType:'json',
				  success: function(data){
					  if(data.status==1){
						dig("绑定成功！");
					  }else{
						dig(data.msg);
					  }
				  },
				  error:function (){
					  //dig('系统繁忙！');
				  }
			});
		},
		getCode:function(){

		}
	}
})
</script>
</body>
</html>