<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>登录</title>
        <link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/style.css">
        <script type="text/javascript" src="{$_PUBLIC}/js/jquery.min.js"></script>
    </head>
    <body>
        <div class="wrap">
            {include file='staticpage_header_other.phtml'}
            <div class="content">
                <div class="loginCont">
                    <form name="LoginForm" method="post"> 
                        <h2>管理登录</h2>
                        <div class="inputBox placeholder">
                            <input type="text" name="username" style="width:378px;">
                            <span>输入账号</span>
                        </div>
                        <div class="inputBox placeholder">
                            <input type="password" name="password" style="width:378px;">
                            <span>输入密码</span>
                        </div>
                        <p class="clearfix rq_remember"><a href="javascript:;"><span></span>记住密码</a></p>
                        <input type="submit" name="submit" value="  登 陆  " class="rq_loginBtn" /> 
                    </form>
                </div>
            </div>
            {include file='staticpage_footer.phtml'}
        </div>
        <script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
    </body>
</html>