{extends file='ztemp/main.phtml'}
{block name=title}申请审批{/block}
{block name=head}
{literal}
<script type="text/javascript" src="/statics/js/jquery.min.js"></script>
<script type="text/javascript" src="/statics/js/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>

<style type="text/css">
    body{font-family: Arial, '宋体';margin:0 auto;padding:0; background:url({/literal}{$_PUBLIC}{literal}/upload_photo/images/bg.jpg) repeat;font-size:12px;color:#000;}
    .container { width:800px; margin:0px auto; }
    .section { background-color:#fff; padding:20px;}
    .row{ width:661px; overflow:hidden; margin-top:20px;line-height:30px;padding-left:94px;}
    .row span.label{float:left;position:relative;line-height:30px;margin-left:-94px;width:84px;text-align:right; color:#5b5b5b;}
    .btn_submit {background:url({/literal}{$_PUBLIC}{literal}/upload_photo/images/submit.gif) no-repeat;width:70px;height:29px;border:0;}
</style>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        申请审批
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST" action="/approval/add">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">标题：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="title" value="{$title}" />
                        <span>标题</span>
                    </div>
                </div>
                <div class="selectBox fl">
                    <div class="mySelect">
                        <select name="deparment_id" id="deparment_id" class="selectmenu" style="width:200px" >
                            <option value="0">选择部门</option>
                        </select>
                    </div>
                </div>
                <div class="selectBox fl">
                    <div class="mySelect">
                        <select name="user_id" id="user_id" class="selectmenu" style="width:200px" >
                            <option value="0">选择用户</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">备注：</label>
                    <div class="inputBox fl">
                        <textarea type="text" name="comment">{$comment}</textarea>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption clearfix rqRadio">
                    <label class="fl">类型：</label>
                    <div class="myradio fl">
                        <div class="radiobox clearfix">
                            <input type="radio" name="approval_type" value="1" checked="checked" /> 普通
                            <input type="radio" name="approval_type" value="2" /> 紧急
                            <input type="radio" name="approval_type" value="3" /> 重要
                        </div>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="row">
                    <label class="fl"></label>
                    <input type="file" name="name" id="fj" value="" />
                    <input type="hidden" name="file_name" id="file_name" value="" />
                </div>
            </div>
            <div class="rqLine">
                <div class="rqOption clearfix">
                    <label class="fl"></label>
                    <div class="fl">
                        <div class="rqLine">
                            <div class="rqOption fl">
                                <a href="javascript:document.form.submit();" class="blueBtn">保存</a>
                            </div>
                            <div class="rqOption fl">
                                <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="id" value="{$id}">
        </form>
    </div>
</div>
{literal}
<link href="/statics/upload_photo/uploadify/uploadify.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="/statics/upload_photo/uploadify/jquery.uploadify-3.1.min.js?ver={/literal}{rand(0,9999)}{literal}"></script>
<script type="text/javascript" src="/statics/upload_photo/jcrop/jquery.Jcrop.min.js"></script>
<link rel="stylesheet" href="/statics/upload_photo/jcrop/jquery.Jcrop.css" type="text/css" />
<script type="text/javascript">
    $(function () {
        $("#fj").uploadify({
            'auto': true,
            'multi': false,
            'uploadLimit': 1,
            'buttonText': '选择文件',
            'height': 20,
            'width': 90,
            'removeCompleted': false,
            'swf': '/statics/upload_photo/uploadify/uploadify.swf',
            'uploader': '/approval/upload',
            'fileTypeExts': '*',
            'fileSizeLimit': '1024KB',
            'onUploadSuccess': function (file, data, response) {
                var msg = $.parseJSON(data);
                if (msg.result_code == 1) {
                    $("#file_name").val(msg.result_des);
                } else {
                    alert('上传失败');
                }
            },
            'onClearQueue': function (queueItemCount) {
                alert($('#file_name'));
            },
            'onCancel': function (file) {
                alert('The file ' + file.name + ' was cancelled.');
            }
        });
    });
</script>
{/literal}
<script type="text/javascript" src="/statics/js/controllers/orderManage.js"></script>
{/block}