{extends file='ztemp/main.phtml'}
{block name=title}人员管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        人员管理
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST" action="/adminuser/quarters">
            <div class="rqLine">
                <div class="rqOption clearfix">
                    <label class="fl">岗位：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="quarters_id" class="selectmenu">
                                <option>全部</option>
                                {$quarterList}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rqLine">
                <div class="rqOption clearfix">
                    <label class="fl"></label>
                    <div class="fl">
                        <div class="rqLine">
                            <div class="rqOption fl">
                                <input type="hidden" name="user_id" value="{$user_id}">
                                <a href="javascript:document.form.submit();" class="blueBtn">保存</a>
                            </div>
                            <div class="rqOption fl">
                                <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/other.js"></script>{/block}