{extends file='main_new.phtml'}
{block name=body}
<div id="content">
    <!-- 头图 -->
    <div class="banner">
        <div class="detail">
            <h3>智慧燃气平台</h3>
            <p>液化石油气运营综合解决方案</p>
            <ul class="clearfix">
                <li>
                    <span>累计订气数（订单）</span><br>
                    <strong>{$orderTotal}</strong>
                </li>
                <li>
                    <span>已使用智能钢瓶（个）</span><br>
                    <strong>{$bottleTotal}</strong>
                </li>
                <li>
                    <span>已开业门店（个）</span><br>
                    <strong>{$shopTotal}</strong>
                </li>
                <li>
                    <span>已有送气工（人）</span><br>
                    <strong>{$shipperTotal}</strong>
                </li>
                <li class="last">
                    <span>所有员工数（人）</span><br>
                    <strong>{$userTotal}</strong>
                </li>
            </ul>
            <a href="/my/home/createorder" class="orangeBtn">立即订气</a>
        </div>
    </div>
    <div class="w1170">
        <!-- 价格动态 -->
        <div class="priceState">
            <div class="title clearfix">
                <h3 class="fl">实时订单</h3>
                <div class="fl position">
                    <span></span>
                    定位&nbsp;河北沧州&nbsp;&nbsp;<a href="javascript:void(0);">[选择区域]</a>
                </div>
                <div class="fr classify">
                    <a href="javascript:void(0);" class="active">订单</a>
                    <a href="javascript:void(0);">5kg</a>
                    <a href="javascript:void(0);">15kg</a>
                    <a href="javascript:void(0);">50kg</a>
                </div>
            </div>
            <div class="detail clearfix">
                <i class="icon" id="icon"></i>
                <div class="fl menu">
                    <a href="javascript:;" class="prevBtn">&lt;</a>
                    <a href="javascript:;" class="nextBtn">&gt;</a>
                    <div class="slide" id="tab">
                        <ul class="clearfix">
                            {if $shopBottle neq ''}
                            {foreach $shopBottle as $value}
                            <li>
                                <h4>{$shopObject[$value['shop_id']]['shop_name']}</h4>
                                <div class="price clearfix up">
                                    <span class="fl">{$value['fs_name']}</span>
                                    <strong class="fl">{$value['fs_num']}</strong>
                                    <i class="fl"></i>
                                </div>
                                <p>气站</p>
                            </li>
                            {/foreach}
                            {/if}
                        </ul>
                    </div>
                </div>
                <div class="chart fr">
                    <p>订单走势</p>
                    <div id="container" style="width:250px;height:160px;"></div>
                </div>
                <span class="line"></span>
            </div>
        </div>
        <!-- 为什么要用智慧燃气 -->
        <div class="youshi">
            <h3>为什么要用智慧燃气？</h3>
            <ul class="clearfix">
                <li class="clearfix">
                    <div class="pic fl"></div>
                    <div class="fl detail">
                        <h4>多渠道便捷订气</h4>
                        <p>APP订气、微信订气、Web端订气、电话订气，实现客户的随时随地便捷订气，大幅提升用户应用体验。</p>
                    </div>
                </li>
                <li class="clearfix">
                    <div class="pic pic2 fl"></div>
                    <div class="fl detail">
                        <h4>高效智能管理平台</h4>
                        <p>信息化智能管理平台大幅优化液化气灌装站的管理流程和管理效率，精准的数据统计，辅助快速决策，抢占市场先机。</p>
                    </div>
                </li>
                <li class="clearfix">
                    <div class="pic pic3 fl"></div>
                    <div class="fl detail">
                        <h4>物联网+互联网</h4>
                        <p>智能钢瓶的物联网信息交互与互联网应用、管理平台有机结合，更加高效、更加安全</p>
                    </div>
                </li>
                <li class="clearfix">
                    <div class="pic pic4 fl"></div>
                    <div class="fl detail">
                        <h4>优化运营流程</h4>
                        <p>解决灌装站存在的难以解决的核心问题，大幅降低钢瓶流失率、优化运营管理化繁为简、精准实时的账目统计、降低人工成本。</p>
                    </div>
                </li>
                <li class="clearfix">
                    <div class="pic pic5 fl"></div>
                    <div class="fl detail">
                        <h4>先进的管理输出</h4>
                        <p>针对各合作气站提供标准化的管理体系至高效、统一、快速的运营服务。</p>
                    </div>
                </li>
                <li class="clearfix">
                    <div class="pic pic6 fl"></div>
                    <div class="fl detail">
                        <h4>用户的放心选择</h4>
                        <p>100%液化气的灌装生产和到家的专业换装、安全宣讲保障用户安全用气，增加用户的忠诚度。</p>
                    </div>
                </li>
            </ul>
        </div>
        <!-- 加入智慧平台 -->
        <div class="join">
            <h3>加入智慧燃气平台</h3>
            <ul>
                <li class="clearfix">
                    <dl class="fl">
                        <dt>普通用户</dt>
                        <dd>通过手机、网站、微信</dd>
                        <dd>在线订气</dd>
                        <dd>自动匹配最近气站</dd>
                    </dl>	
                    <div class="pic fl"></div>
                    <div class="fl regist">
                        <a href="javascript:;" class="orangeBtn mb24">立即注册</a>
                        <p>手机号直接注册</p>
                    </div>
                </li>
                <li class="clearfix li2">
                    <dl class="fl">
                        <dt>液化气站</dt>
                        <dd>互联网+战略快速升级</dd>
                        <dd>智慧平台工业4.0</dd>
                    </dl>
                    <div class="pic pic2 fl"></div>
                    <div class="fl regist">
                        <a href="javascript:;" class="redBtn mb24">立即申请</a>
                        <p>营业执照</p>
                        <p>燃气经营许可证</p>
                        <p>充装证</p>
                    </div>
                </li>
            </ul>
        </div>
        <!-- 行业动态 安全常识 -->
        {include file='main_new_dynamic.phtml'}
    </div>
</div>
{/block}