{extends file='ztemp/main.phtml'}
{block name=title}区域管理{/block}
{block name=head}
{literal}
<script type="text/javascript" src="/statics/js/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
<script type="text/javascript" src="/statics/js/region_select.js"></script>
<script>
    $(function ($) {
        var sheng = "{/literal}{$sheng}{literal}";
        var shi = "{/literal}{$shi}{literal}";
        var shi_name = "{/literal}{$shi_name}{literal}";
        var xian = "{/literal}{$xian}{literal}";
        var xian_name = "{/literal}{$xian_name}{literal}";
        region_util({
            v1_select: '.region_1',
            v2_select: '.region_2',
            v3_select: '.region_3',
            v4_select: '.region_4',
            request_param: {
                opt_cat: 'list',
            },
            r_param: {
                sheng: sheng,
                shi: shi,
                shi_name: shi_name,
                xian: xian,
                xian_name: xian_name
            }
        });
    });
</script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        区域管理
        <span></span>
    </div>
    <div class=" contRList">
        <form name="form" method="POST" action="/regionmanage/add"> 
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">市：</label>
                    <div class="selectBox fl placeholder">
                        <select name="region_1" class="selectmenu region_1"></select>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">区/县：</label>
                    <div class="selectBox fl">
                        <select name="region_2" class="selectmenu region_2"></select>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">添加街道：</label>
                    <div class="inputBox fl">
                        <textarea name="region_name" style="width:410px;">{$regionData['region_name']}</textarea>
                    </div>
                </div>
            </div>
            <div class="rqLine">
                <div class="rqOption clearfix">
                    <label class="fl"></label>
                    <div class="fl">
                        <div class="rqLine">
                            <div class="rqOption fl">
                                <a href="javascript:document.form.submit();" class="blueBtn">保存</a>
                            </div>
                            <div class="rqOption fl">
                                <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                            </div>
                        </div>
                    </div>
                </div> 
            </div> 
            <input type='hidden' name='pid' value='{$pid}' style="width:150px;"/>
        </form> 
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/other.js"></script>{/block}