{extends file='main.phtml'}
{block name=rtitle}
配件管理
{/block}
{block name=body}
{literal}
<script>
    $(function () {
        
    });
</script>
{/literal}
<form name="form" method="POST" action="/products/add">
    <div class="rqLine clearfix">
        <div class="rqOption fl">
            <label class="fl">物品编号：</label>
            <div class="inputBox fl placeholder">
                <input type="text" name="products_no" value="{$productno}" style="width:150px;">
                <span>物品编号</span>
            </div>
        </div>
        <div class="rqOption fl">
            <label class="fl">物品名称：</label>
            <div class="inputBox fl placeholder">
                <input type="text" name="products_name" value="" style="width:150px;">
                <span>物品名称</span>
            </div>
        </div>
    </div>
    <div class="rqLine clearfix">
        <div class="rqOption fl">
            <label class="fl">规格：</label>
            <div class="inputBox fl placeholder">
                <input type="text" name="products_norm" style="width:150px;">
                <span>规格</span>
            </div>
        </div>
        <div class="rqOption fl">
            <label class="fl">品牌：</label>
            <div class="inputBox fl placeholder">
                <input type="text" name="products_brand" style="width:150px;">
                <span>品牌</span>
            </div>
        </div>    
    </div>
    <div class="rqLine clearfix">
        <div class="rqOption fl">
            <label class="fl">单价：</label>
            <div class="inputBox fl placeholder">
                <input type="text" name="products_price" style="width:150px;">
                <span>单价</span>
            </div>
        </div>
        <div class="rqOption fl clearfix">
            <label class="fl">产地：</label>
            <div class="inputBox fl placeholder">
                <input type="text" name="products_address" style="width:435px;">
                <span>产地</span>
            </div>
        </div>
    </div>
    <div class="rqLine clearfix">
        <div class="rqOption clearfix">
            <label class="fl">备注：</label>
            <div class="fl">
                <textarea name="products_comment"></textarea>
                <div  class="rqLine">
                    <div class="rqOption fl">
                        <a href="javascript:document.form.submit();" class="blueBtn">下一步</a>
                    </div>
                    <div class="rqOption fl">
                        <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" name="id" value="">
</form>
{/block}