{extends file='ztemp/main.phtml'}
{block name=title}折旧订单{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=operate}
<div class="contRItem">
    <div class="contRTitle">
        折旧订单
        <span></span>
    </div>
    <div class="contRList">
        <div class="tpData">
            <ul class="clearfix">
                <li>
                    <p>今日订单数量</p>
                    <span>{$nowTj}</span>
                </li>
                <li  class="greenBg">
                    <p>累计订单数量</p>
                    <span>{$ext['count']}</span>
                </li>
            </ul>
        </div>
    </div>
</div>
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        折旧订单
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">订单号：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="order_sn" value="{$param['order_sn']}" style="width:120px;">
                        <span>输入订单号</span>
                    </div>
                </div>
                <div class="rqOption fl">
                    {if isset($is_show_shop) && !empty($is_show_shop)}
                    <div class="rqOption fl"><input type="hidden" name="shop_id" value="{$is_show_shop}" /></div>
                    {else}
                    <label class="fl">配送站点：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="shop_id" class="selectmenu"  style="width:144px;">
                                <option value="">选择站点</option>
                                {foreach $shopObject as $k=>$v}
                                {if $k eq $param['shop_id']}
                                <option value="{$k}" selected="selected">{$v['shop_name']}</option>
                                {else}
                                <option value="{$k}">{$v['shop_name']}</option>
                                {/if}
                                {/foreach}
                            </select>
                        </div>
                    </div>
                    {/if}
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">送气工：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="shipper_name" value="{$param['shipper_name']}" style="width:120px;">
                        <span>输入送气工姓名</span>
                    </div>
                </div>
                <div class="rqOption fl">
                    <label class="fl">客户电话：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="mobile" value="{$param['mobile']}" style="width:120px;">
                        <span>输入正确电话号码</span>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">订单时间：</label>
                    <div class="riliInputBox fl">
                        <div class="riliInput fl">
                            <input type="text" name="time_start" style="width:152px;" id="time_start" value="{$param['time_start']}">
                        </div>
                        <span class="fl">至</span>
                        <div class="riliInput fl">
                            <input type="text" name="time_end" id="time_end" style="width:152px;" value="{$param['time_end']}">
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                    <input type="submit" name="submit" class="blueBtn" value="搜索" />
                </div>
            </div>
        </form>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>订单号</th>
                        <th>时间</th>
                        <th>客户电话</th>
                        <th>订单金额</th>
                        <th>残液重量</th>
                        <th>隶属门店</th>
                        <th>订单状态</th>
                    </tr>
                </thead>
                <tbody>
                    {if count($ext['list']) > 0}
                    {foreach $ext['list'] as $value}
                    <tr>
                        <td>{$value['order_sn']}</td>
                        <td>{date('m-d H:i',$value['time_created'])}</td>
                        <td>{$value['mobile']}</td>
                        <td>{$value['money']}</td>
                        <td>{$value['weight']}</td>
                        <td>{$shopObject[$value['shop_id']]['shop_name']}</td>
                        <td>{($value['status'] == 1) ? '已结算' : '未结算'}</td>
                    </tr>
                    {/foreach}
                    {else}
                    <tr><td colspan="10">暂时还没有数据</td></tr>
                    {/if}
                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$page}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count'] / 15)}">
            <input type="hidden" class="paramlist" value="{$getparamlist}" />
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/orderManage.js"></script>{/block}