{extends file='znewtemp/main.phtml'}
{block name=title}订单管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/style.css">
<script type="text/javascript" src="/statics/znewhome/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="fr right-cont">
    <!-- 头部 -->
    <div class="clearfix title mb30">
        <div class="fl">
            <h3>订单管理</h3>
            <p>销售管理 > 订单管理</p>
        </div>	
        <div class="fr">
            <a href="javascript:void(0);" class="createBtn mt10">+创建订单</a>
        </div>
    </div>
    <!-- 数据统计 -->
    <div class="dataMenu dataMenu2 mb24  pl186">
        <div class="bgBtn">
            <p>今日订单</p>
            <strong>{$nowTj}</strong>
        </div>
        <ul class="clearfix">
            {if $statusTj neq ''}
            {foreach $statusTj as $tVal}
            <li>
                <p>{$orderStatus[$tVal['status']]}</p>
                <strong>{$tVal['total']}</strong>
            </li>
            {/foreach}
            {/if}
            <li>
                <p>累积订单</p>
                <strong>{$ext['count']}</strong>
            </li>
        </ul>	
    </div>
    <!-- 条件查询 -->
    <div class="refer mb34">
        <form name="form" method="POST">
            <div class="mb10 clearfix lineData">
                <label class="fl">配送站点：</label>
                <div class="fl chooseOption" style="width:800px">
                    {foreach $shopObject as $k=>$v}
                    {if $k eq $param['shop_id']}
                    <a href="javascript:void(0);" class="active" data-value="{$k}">{$v['shop_name']}</a>
                    {else}
                    <a href="javascript:void(0);" data-value="{$k}">{$v['shop_name']}</a>
                    {/if}
                    {/foreach}
                </div>
                <input type="hidden" name="shop_id" value="{$param['shop_id']}">
            </div>
            <div class="mb20 clearfix lineData">
                <div class="fl mr60">
                    <label class="fl">订单号：</label>
                    <input type="text" style="width:135px" name="order_sn" id="order_sn" value="{$param['order_sn']}" placeholder="输入订单号" class="fl">
                </div>
                <div class="fl">
                    <label class="fl">订单状态：</label>
                    <div class="fl chooseOption" style="width:490px">
                        {if $orderStatus neq ''}
                        {foreach $orderStatus as $ukey => $usVal}
                        {if $ukey eq $param['status']}
                        <a href="javascript:void(0);" class="active" data-value="{$ukey}">{$usVal}</a>
                        {else}
                        <a href="javascript:void(0);" data-value="{$ukey}">{$usVal}</a>
                        {/if}
                        {/foreach}
                        {/if}
                    </div>
                    <input type="hidden" name="status" value="{$param['status']}">
                </div>
            </div>
            <div class="mb20 clearfix lineData">
                <div class="fl mr60">
                    <label class="fl">客户姓名：</label>
                    <input type="text" name="username" value="{$param['username']}" style="width:135px" placeholder="输入客户姓名"  class="fl">
                </div>
                <div class="fl mr60">
                    <label class="fl">客户电话：</label>
                    <input type="text" name="mobile" value="{$param['mobile']}" style="width:135px" placeholder="输入客户电话"  class="fl">
                </div>
                <div class="fl">
                    <label class="fl">客户类型：</label>
                    <div class="fl chooseOption" style="width:200px">
                        {if $userType neq ''}
                        {foreach $userType as $utVal}
                        {if $utVal['id'] eq $param['kehu_type']}
                        <a href="javascript:void(0);" class="active" data-value="{$utVal['id']}">{$utVal['typemanagername']}</a>
                        {else}
                        <a href="javascript:void(0);" data-value="{$utVal['id']}">{$utVal['typemanagername']}</a>
                        {/if}
                        {/foreach}
                        {/if}
                    </div>
                    <input type="hidden" name="kehu_type" value="{$param['kehu_type']}">
                </div>
            </div>
            <div class="clearfix lineData">
                <div class="fl mr60">
                    <label class="fl">送气工：</label>
                    <input type="text" name="shipper_name" value="{$param['shipper_name']}" style="width:135px" placeholder="输入送气工姓名"  class="fl">
                </div>
                <div class="fl mr15">
                    <label class="fl">详细地址：</label>
                    <input type="text" style="width:330px" placeholder="输入详细地址" name="address" value="{$param['address']}" class="fl">
                </div>
                <a href="javascript:void(0);" id="searchBtn" class="fl">搜索</a>
            </div>
        </form>
    </div>
    <!-- 订单查询结果 -->
    <div class="result">
        <div class="clearfix title mb10">
            <p class="fl">订单查找结果：</p>
            <div class="fr chooseDate">
                <span class="fl">选择时段：</span>
                <div class="doubleRili fl">
                    <input type="text" id="start" value="{$param['time_start']}" name="time_start" style="width:80px;">
                </div>
                <span class="fl plr8">到</span>
                <div class="doubleRili fl">
                    <input type="text" id="end" name="time_end" value="{$param['time_end']}" style="width:80px;">
                </div>
                <a href="javascript:void(0);" class="fl">确定</a>
            </div>
        </div>
        <div class="table2 mb34">
            <table>
                <thead>
                    <tr>
                        <th class="borderRight">下单时间</th>
                        <th>下单号</th>
                        <th>客户信息</th>
                        <th>订单金额</th>
                        <th>订单来源</th>
                        <th>隶属门店</th>
                        <th>订单状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {if count($ext['list']) > 0}
                    {foreach $ext['list'] as $value}
                    <tr>
                        <td class="borderRight">{date('m-d H:i',$value['ctime'])}</td>
                        <td>{$value['order_sn']}</td>
                        <td>{$value['username']}[{(isset($userType[$value['kehu_type']])) ? $userType[$value['kehu_type']]['typemanagername'] : ''}]<br>{$value['mobile']}</td>
                        <td class="redColor"><strong>￥{($value['status'] eq 4) ? $value['pay_money'] : $value['money']}</strong></td>
                        <td>{(isset($ordersource[$value['ordertype']])) ? $ordersource[$value['ordertype']] : '订单来源'}</td>
                        <td>{$shopObject[$value['shop_id']]['shop_name']}</td>
                        <td>{(isset($orderStatus[$value['status']])) ? $orderStatus[$value['status']] : ''}</td>
                        <td class="operate">
                            <a href="/order/info?ordersn={$value['order_sn']}&shop_id={$value['shop_id']}&temptype=new">详情 &gt;</a>
                            {if $value['shipper_mobile'] eq '' && $value['status'] neq 6 && $value['status'] neq 2}
                            <span>|</span>
                            <a href="javascript:;" class="paifaBtn" ordersn="{$value['order_sn']}" ordershop="{$value['shop_id']}">派发</a>
                            {/if}
                            {if $value['status'] eq 4 && $value['is_settlement'] eq 2}
                            <span>|</span>
                            <a href="/order/qkinfo?ordersn={$value['order_sn']}&shop_id={$value['shop_id']}">欠款</a>
                            {/if}
                        </td>
                    </tr>
                    {/foreach}
                    {else}
                    <tr><td colspan="8">暂时还没有数据</td></tr>
                    {/if}
                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom mb50">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$page}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count'] / 15)}">
            <input type="hidden" class="paramlist" value="{$getparamlist}" />
        </div>
    </div>
</div>
{/block}
{block name=fjs}
<script type="text/javascript" src="/statics/znewhome/js/controllers/comment.js"></script>
<script type="text/javascript" src="/statics/znewhome/js/controllers/dingdanguanliCtrl.js"></script>
{/block}