{extends file='znewtemp/main.phtml'}
{block name=title}组织架构{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/style.css">
<script type="text/javascript" src="/statics/znewhome/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="fr right-cont">
    <!-- 头部 -->
    <div class="clearfix title">
        <div class="fl">
            <h3>组织架构</h3>
            <p>人员 > 组织架构</p>
        </div>	
        <div class="fr">
            <a href="/adminuser/add" class="blueBtn3 mt10">+添加人员</a>
        </div>
    </div>
    <!-- 数据统计 -->
    <div class="dataMenu mb40 zzjgMenu pl190">
        <div class="bgBtn">
            <p>组织架构</p>
            <strong>{$organizationNum}</strong>个部门
        </div>
        <ul class="clearfix">
            <li>
                <p>所有人员</p>
                <strong>{$adminUserData[0] + $adminUserData[1] + $adminUserData[2]}</strong>
            </li>
            <li>
                <p>在职人员</p>
                <strong>{$adminUserData[0]}</strong>
            </li>
            <li>
                <p>送气工</p>
                <strong>{$shipperNum}</strong>
            </li>
            <li>
                <p>离职人员</p>
                <strong>{$adminUserData[1] + $adminUserData[2]}</strong>
            </li>
        </ul>	
    </div>
    <!-- 图表 -->
    <div class="clearfix">
        <div class="fl departData">
            <h3>人员部门数据</h3>
            <ul class="clearfix">
                {if $returnData neq ''}
                {foreach $returnData as $orgUser}
                <li>{$orgUser['title']}<span></span>{$orgUser['total']}人</li>
                {/foreach}
                {/if}
            </ul>
        </div>
        {literal}
        <script type="text/javascript" src="/statics/js/jquery.min.js"></script>
        <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
        <script>
            $(function () {
                
                $('#container').highcharts({
                    chart: {
                        plotBackgroundColor: null,
                        plotBorderWidth: null,
                        plotShadow: false
                    },
                    title: {
                        text: ''
                    },
                    credits: {
                        enabled: false // 禁用版权信息
                    },
                    tooltip: {
                        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    },
                    plotOptions: {
                        pie: {
                            allowPointSelect: true,
                            cursor: 'pointer',
                            dataLabels: {
                                enabled: true,
                                color: '#000000',
                                connectorColor: '#000000',
                                format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                            }
                        }
                    },
                    series: [{
                            type: 'pie',
                            name: '人员部门数据',
                            data: {/literal}{$returnTotal}{literal}
                        }]
                });
            });
        </script>
        {/literal}
        <!-- 饼状图 -->
        <div class="fr" id="container" style="width:460px;height:280px;"></div>
    </div>
    <!-- 表格 -->
    <div class="zzjgTabel">
        <div class="title">
            <span>岗位</span>
            <span>人员姓名/手机</span>
        </div>
        <div class="box">
            <div class="cont">
                {$list}
            </div>
        </div>
    </div>
</div>
{/block}
{block name=fjs}
<script type="text/javascript" src="/statics/znewhome/js/controllers/comment.js"></script>
{/block}