{extends file='ztemp/main.phtml'}
{block name=title}供应商管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRList">
        <form name="form" method="POST" action="/supplier/add">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">供应商号：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="supplier_no" value="{$supplier_no}" style="width:150px;">
                        <span>供应商号</span>
                    </div>
                </div>
                <div class="rqOption fl">
                    <label class="fl">供应商名称：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="name" value="{$name}" style="width:150px;">
                        <span>供应商名称</span>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">供应商类别：</label>
                    <div class="selectBox fl" style="width:172px;">
                        <div class="mySelect">
                            <select name="type" id="typelist" class="selectmenu">
                                <option value="0" >请选择</option>
                                {foreach $type as $k => $v}
                                {if $param['type'] eq $k}
                                <option value="{$k}" selected="selected">{$v}</option>
                                {else}
                                <option value="{$k}">{$v}</option>
                                {/if}
                                {/foreach}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <label class="fl">产品类别：</label>
                    <div class="selectBox fl" style="width:172px;">
                        <div class="mySelect">
                            <select name="goods_type" id="goods_type" class="selectmenu">
                                <option value="0" >请选择</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">联系人：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="username" value="{$username}" style="width:150px;">
                        <span>联系人</span>
                    </div>
                </div>
                <div class="rqOption fl">
                    <label class="fl">联系方式：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="tel" value="{$tel}" style="width:150px;">
                        <span>联系方式</span>
                    </div>
                </div>    
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl clearfix">
                    <label class="fl">详细地址：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="address" value="{$address}" style="width:435px;">
                        <span>输入详细地址</span>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption clearfix">
                    <label class="fl">备注：</label>
                    <div class="fl">
                        <textarea name="comment">{$comment}</textarea>
                        <div  class="rqLine">
                            <div class="rqOption fl">
                                <a href="javascript:document.form.submit();" class="blueBtn">提交</a>
                            </div>
                            <div class="rqOption fl">
                                <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="id" value="{$id}" />
        </form>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/other.js"></script>{/block}