{extends file='ztemp/main.phtml'}
{block name=title}供应商管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        供应商管理
        <span></span>
        <!--a href="javascript:;" class="blueBtn11 addGongyingshang">添加供应商</a-->
        <a href="/supplier/add" class="blueBtn11">添加供应商</a>
    </div>
    <div class="contRList">
        <form name="form" method="POST">
            <div class="rqLine clearfix">
                <div class="rqOption rqOption4 fl">
                    <label class="fl">供应商编号：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="supplier_no" value="{$param['supplier_no']}" style="width:148px;">
                    </div>
                </div>
                <div class="rqOption rqOption4 fl">
                    <label class="fl">供应商名称：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="name" value="{$param['name']}" style="width:148px;">
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption rqOption4 fl">
                    <label class="fl">供应商类别：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="type" id="typelist" class="selectmenu" style="width:170px;">
                                <option value="0" >请选择</option>
                                {foreach $type as $k => $v}
                                {if $param['type'] eq $k}
                                <option value="{$k}" selected="selected">{$v}</option>
                                {else}
                                <option value="{$k}">{$v}</option>
                                {/if}
                                {/foreach}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="rqOption rqOption4 fl">
                    <label class="fl">产品类别：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="" name="goods_type" id="goods_type" class="selectmenu" style="width:170px;"></select>
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                    <input type="submit" name="submit" class="blueBtn" value="搜索" />
                </div>
            </div>
        </form>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>供应商编号</th>
                        <th>供应商类别</th>
                        <th>产品类别</th>
                        <th class="w100">供应商名称</th>
                        <th>联系人</th>
                        <th>联系电话</th>
                        <th class="w100">详细地址</th>
                        <th>录入</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody> 
                    {if $ext['list'] neq ''}
                    {foreach $ext['list'] as $value}
                    <tr>
                        <td>{$value['supplier_no']}</td>
                        <td>{$type[$value['type']]}</td>
                        <td>{$value['goods_name']}</td>
                        <td>{$value['name']}</td>
                        <td>{$value['username']}</td>
                        <td>{$value['tel']}</td>
                        <td>{$value['address']}</td>
                        <td>{$value['admin_username']}</td>
                        <td class="tableBtn">
                            <a href="/supplier/edit?id={$value['id']}&type={$value['type']}">修改</a>
                            <span>|</span>
                            <a href="javascript:;" class="del_supplier" supplier_id="{$value['id']}" supplier_type="{$value['type']}">删除</a>
                        </td>
                    </tr>
                    {/foreach}
                    {else}
                    <tr>
                        <td colspan="9">暂时还没有数据</td>
                    </tr>
                    {/if}
                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$param['page']}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
            <input type="hidden" class="paramlist" value="{$getparamlist}" />
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/gongyingshangManage.js"></script>{/block}