{extends file='main.phtml'}
{block name=rtitle}残液支出{/block}
{block name=body}
<div class="orderList contRList">
    <form name="form" method="POST">

        <div class="rqLine clearfix">
            {if $shop_id>0}
            <input type="hidden" name = 'shop_id' value='{$shop_id}' />
            {else}
            <div class="rqOption fl">
                <label class="fl">门店列表：</label>
                <div class="selectBox fl" style="width:172px;">
                    <div class="mySelect">
                        <select name="shop_id" class="selectmenu">
                            <option value="0">请选择</option>
                            {foreach $shopObject as $k=>$v}
                            <option value="{$k}" {if $k eq $param['shop_id']}selected="selected"{/if}>{$v['shop_name']}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
            </div>
            {/if}
            <div class="rqOption fl">
                <label class="fl">时间：</label>
                <div class="riliInputBox fl">
                    <div class="riliInput fl">
                        <input type="text" style="width:150px;" name="start_time" value="{$param['start_time']}" id="time_start">
                    </div>
                    <span class="fl">至</span>
                    <div class="riliInput fl">
                        <input type="text" id="time_end" name="end_time" value="{$param['end_time']}" style="width:150px;">
                    </div>
                </div>
            </div>
        </div>

        <div class="rqLine clearfix">
            <div class="rqOption fl">
                <input type="submit" class="blueBtn" value='查询'>
            </div>
        </div>
    </form>
    <div class="contRItem">
        <div class="contRTitle">
            数据统计
            <span></span>
        </div>
        <div class="contRList countData">
            <p> 
                {if $statusTj neq ''}
                {foreach $statusTj as $tVal}
                {$shopObject[$tVal['shop_id']]['shop_name']}：<span>{$tVal['total']}</span>
                {/foreach}
                {/if}
            </p>
        </div>
    </div>
    <table>
        <tr>
            <td>订单号</td>
            <td>门店</td>
            <td>残液支出</td>
            <td>时间</td>
        </tr>

        {if $ext neq ''}
        {foreach $ext['list'] as $value}
        <tr>
            <td>{$value['order_sn']}</td>
            <td>{$shopObject[$value['shop_id']]['shop_name']}</td>
            <td>{$value['raffinat']}</td>
            <td>{date('Y-m-d',$value['ctime'])}</td>
        </tr>
        {/foreach} 
        {/if}
    </table>

    <div class="table-pages pageNav clearfix" id="pageNav"></div>
</div>
<script type="text/javascript">
    var page = {$page}
    var totalPage = {ceil($ext['count']/15)};
</script>
<script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
{/block}