{extends file='znewtemp/main_home.phtml'}
{block name=title}送气工位置{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/jquery.circliful.css">
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/style.css">

<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=GGzsVgy3Ra6GWd6n3Sww2Kdx"></script>
<script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script>

<script type="text/javascript" src="/statics/znewhome/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="content">
    <div id="allmap" style="width:100%;height:800px;overflow:hidden;"></div>
</div>
{/block}
{block name=fjs}
{literal}
<script type="text/javascript">
    // 百度地图API功能	
    //var map = new BMap.Map("allmap");
    //var point = new BMap.Point({/literal}{$poingList}{literal});
    //map.centerAndZoom(point, 15);
    map = new BMap.Map("allmap");
    map.centerAndZoom('沧州', 15);
    
    /*var data_info = [[116.417854, 39.921988, "地址：北京市东城区王府井大街88号乐天银泰百货八层"],
        [116.406605, 39.921585, "地址：北京市东城区东华门大街"],
        [116.412222, 39.912345, "地址：北京市东城区正义路甲5号"]
    ];*/
    
    setTimeout(function(){
        map.setZoom(14);   
    }, 2000);  //2秒后放大到14级
    map.enableScrollWheelZoom(true);    
        
    var data_info =[{/literal}{$maplist}{literal}];
    var opts = {
        width: 250, // 信息窗口宽度
        height: 80, // 信息窗口高度
        title: "送气工相关信息", // 信息窗口标题
        enableMessage: true//设置允许信息窗发送短息
    };
    for (var i = 0; i < data_info.length; i++) {
        var myIcon = new BMap.Icon("/statics/images/sqg.png",new BMap.Size(46,64));
        
        var marker = new BMap.Marker(new BMap.Point(data_info[i][0], data_info[i][1]),{icon:myIcon});  // 创建标注
        var content = data_info[i][2];
        map.addOverlay(marker);               // 将标注添加到地图中
        addClickHandler(content, marker);
    }
    function addClickHandler(content, marker) {
        marker.addEventListener("click", function(e) {
            openInfo(content, e)
        });
    }
    function openInfo(content, e) {
        var p = e.target;
        var point = new BMap.Point(p.getPosition().lng, p.getPosition().lat);
        var infoWindow = new BMap.InfoWindow(content, opts);  // 创建信息窗口对象 
        map.openInfoWindow(infoWindow, point); //开启信息窗口
    }
</script>
{/literal}
{/block}