<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
        <meta name="format-detection" content="telephone=no" />
        <title>我要订气</title>
        <link rel="stylesheet" type="text/css" href="/statics/css/layout.css">
        <link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
        <script type="text/javascript" src="/statics/js/jquery.js"></script>
        <script type="text/javascript" src="/statics/js/jquery-ui.js"></script>
        
    </head>
    <body>
        <div class="wrap dqwrap">
            <div class="content">
                稍等一下马上就来
            </div>
        </div>
        <script type="text/javascript" src="/statics/js/public.js"></script>
    </body>
</html>