<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0"/>
	<title>提交订单</title>
	<link rel="stylesheet" href="/statics/css/base.css"/>
	<link rel="stylesheet" href="/statics/css/style.css"/>
	<script src="/statics/js/jquery-1.8.3.min.js"></script>
	<script src="/statics/js/main.js"></script>
	<script type="text/javascript" src="/statics/js/Vue.min.js"></script>
	<script type="text/javascript" src="/statics/js/vue-resource.min.js"></script>
	{include '../header.phtml'}
</head>
<body id="Vbody">
	<div class="address_detail">
		<div class="l_img">
			<img src="/statics/images/location.png" alt="">
		</div>
		<div class="r_con">
			<ul>
				<li>
					<span class="user_name">[[user.user_name]]</span>
					<span class="user_tel">[[user.mobile_phone]]</span>
				</li>
				<li>
					[[user.address]]
				</li>
			</ul>
		</div>
	</div>
	<div class="t_"></div>
	<div class="goods_detail">
		<table>
			<tr>
				<td>商品名称</td>
				<td>规格</td>
				<td>单价</td>
				<td>数量</td>
			</tr>
			<template v-for="info in order.goods">
			<tr>
				<td>[[info.name]]</td>
				<td>[[info.type]]</td>
				<td>[[info.price]]</td>
				<td>[[info.num]]</td>
			</tr>
			</template>
			
		</table>
	</div>
	<div class="else-info">
		<ul>
			<li><span>优惠券</span><span>-[[order.promotion_money]]</span></li>
			<li><span>配送时间</span><span>[[order.sendtime_str]]</span></li>
			<li><span>订单备注</span><span>[[order.comment]]</span></li>
		</ul>
	</div>
	<div class="f_submit">
		<div class="l_sub">
			订单金额：
			<img src="/statics/images/money.png" alt="">
			<span class="money">[[totalprice]]</span>
		</div>
		<div class="r_btn submit_btn">立即支付</div>
	</div>
	<!-- 选择支付方式页 -->
	<div class="mask"></div>
	<div class="pay_mode">
		<h1>选择支付方式</h1>
		<ul>
			<li><img class="icon_pay" src="/statics/images/xianj.png" alt="">货到付款<img class="choose c_circle" src="/statics/images/btn_f.png" alt=""></li>
			<li><img class="icon_pay" src="/statics/images/weixin.png" alt="">微信缴费<span>（功能暂未开放）</span><img class="c_circle" src="/statics/images/btn_f.png" alt=""></li>
		</ul>
		<div class="f_pay">
			<div class="l_cancel">取消</div>
			<div class="r_sure">确定</div>
		</div>
	</div>
<script type="text/javascript">
var id = GetQueryString('id');
new Vue({
	el: '#Vbody',
	ready: function() {
		this.getOrder();
		this.getUser();
	},
	methods: {
		//获取订单
		getOrder:function(){
			this.$http.get('/wx/order/getordertmp?id='+id, function(data, status, request) {
				if(data.status==1){
					var totalpric = 0;
					var goods=data.data.goods;
					for(var i in goods){
						totalpric += goods[i].num*goods[i].price; 
					}
					totalpric -= data.data.promotion_money; 
					this.$set('totalprice',totalpric);
					this.$set('order', data.data);
				}else{

				}
				
			});
		},
		getUser:function(){
			this.$http.get('/wx/ucenter/getuser', function(data, status, request) {
				if(data.status==1){
					this.$set('user', data.data);
				}else{
					this.$set('user', '');
				}
			});
		},
	}
})
</script>
</body>
</html>