{extends file='ztemp/main.phtml'}
{block name=title}配件种类设置{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        配件种类设置
        <span></span>
        <a href="javascript:;" class="blueBtn8 addShangpin">添加配件种类</a>
    </div>
    <div class="contRList">
        <div class="rqTabItem">
            <table>
                <tr>
                    <td>编号</td>
                    <td>配件名称</td>
                    <td>备注</td>
                    <td>操作</td>
                </tr>
                {if $ext['list'] neq ''}
                {foreach $ext['list'] as $value}
                <tr>
                    <td>{$value['specificationsn']}</td>
                    <td>{$value['name']}</td>
                    <td>{$value['comment']}</td>
                    <td>
                        <a href="/specifications/edite?id={$value['id']}">修改</a>|
                        <a href="/specifications/del?id={$value['id']}">删除</a>
                    </td>
                </tr>
                {/foreach} 
                {/if}
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$page}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/shangpinzhongleiManage.js"></script>{/block}