<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="renderer" content="webkit">
        <title>{block name=title}瑞气科技管理系统{/block}</title>
        {block name=head}{/block}
        <link rel="stylesheet" type="text/css" href="/statics/css/common.css">
    </head>
    <body>
        <div class="wrap">
            {include file='ztemp/staticpage_header_new.phtml'}
            <div class="content clearfix">
                <!-- 左侧导航 -->
                {block name=right}{include file='ztemp/staticpage_left_new.phtml'}{/block}
                <!-- 右侧 -->
                <div class="contRight fr">
                    {block name=operate}{/block}
                    {block name=body}{/block}
                </div>
            </div>
            {include file='ztemp/staticpage_footer_new.phtml'}
        </div>
        <script type="text/javascript" src="/statics/js/comment_old.js"></script>
        {block name=fjs}{/block}
    </body>
</html>