<div class="contLeft fl">
    <ul index="1" style="display:block;">
        <li class="show_active sonLi5"><a href="/index/home" id="show_url_list" class="show_url">统计汇总<span></span></a></li>
        <li class="show_active sonLi5"><a href="/sales/index" id="show_url_list" class="show_url">销售额简报<span></span></a></li>
        <li class="show_active sonLi5"><a href="/finance/report" id="show_url_list" class="show_url">应收款简报<span></span></a></li>
        <li class="show_active sonLi5"><a href="/sales/kehu" id="show_url_list" class="show_url">新开户简报<span></span></a></li>
        <li class="show_active sonLi5"><a href="/sales/quarter" id="show_url_list" class="show_url">回流率简报<span></span></a></li>
        <li class="show_active sonLi5"><a href="/inventory/report" id="show_url_list" class="show_url">库存量简报<span></span></a></li>
        <li class="show_active sonLi5"><a href="/statistics/order" id="show_url_list" class="show_url">订单统计<span></span></a></li>
        <li class="show_active sonLi5"><a href="/statistics/kehu" id="show_url_list" class="show_url">客户统计<span></span></a></li>
    </ul>
    <ul index="2" style="display:none;">
        <li class="show_active sonLi5"><a href="/organize/list" id="show_url_list" class="show_url">组织架构<span></span></a></li>
        <li class="show_active sonLi5"><a href="/news/index" id="show_url_list" class="show_url">消息通知<span></span></a></li>
        <li class="show_active sonLi5"><a href="/approval/index" id="show_url_list" class="show_url">申请审批<span></span></a></li>
        <li class="show_active sonLi5"><a href="/adminuser/index" id="show_url_list" class="show_url">人员管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/shipper/index" id="show_url_list" class="show_url">送气工管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/car/index" id="show_url_list" class="show_url">车辆管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/deposit/index" id="show_url_list" class="show_url">退瓶管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/bottle/index" id="show_url_list" class="show_url">钢瓶管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/losscylinders/index" id="show_url_list" class="show_url">钢瓶流失记录<span></span></a></li>
        <li class="show_active sonLi5"><a href="/stock/bottle" id="show_url_list" class="show_url">配件库存<span></span></a></li>
        <li class="show_active sonLi5"><a href="/stock/sflow" id="show_url_list" class="show_url">门店钢瓶库存<span></span></a></li>
        <li class="show_active sonLi5"><a href="/stock/flow" id="show_url_list" class="show_url">气站钢瓶库存<span></span></a></li>
        <li class="show_active sonLi5"><a href="/security/list" id="show_url_list" class="show_url">安全检查记录<span></span></a></li>
        <li class="show_active sonLi3"><a href="/baseline/bottle" id="show_url_list" class="show_url">钢瓶库存报警<span></span></a></li>
        <li class="show_active sonLi3"><a href="/baseline/gas" id="show_url_list" class="show_url">燃气库存报警<span></span></a></li>
        <li class="show_active sonLi3"><a href="/baseline/product" id="show_url_list" class="show_url">配件库存报警<span></span></a></li>
        <li class="show_active sonLi5"><a href="/statistics/shipper" id="show_url_list" class="show_url">送气工统计<span></span></a></li>
        <li class="show_active sonLi5"><a href="/statistics/filling" id="show_url_list" class="show_url">充装统计<span></span></a></li>
    </ul>
    <ul index="3" style="display:none;">
        <li class="show_active sonLi5"><a href="/order/index" id="show_url_list" class="show_url">订单管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/custum/index" id="show_url_list" class="show_url">客户管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/shop/index" id="show_url_list" class="show_url">门店管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/tousu/index" id="show_url_list" class="show_url">投诉管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/baoxiu/index" id="show_url_list" class="show_url">报修管理<span></span></a></li>
        <!--li class="show_active sonLi5"><a href="" id="show_url_list" class="show_url">商品价格<span></span></a></li-->
    </ul>
    <ul index="4" style="display:none;">
        <li class="show_active sonLi5"><a href="/deposit/income" id="show_url_list" class="show_url">押金收入<span></span></a></li>
        <li class="show_active sonLi5"><a href="/finance/index" id="show_url_list" class="show_url">应收账款<span></span></a></li>
        <li class="show_active sonLi5"><a href="/order/salesrevenue" id="show_url_list" class="show_url">销售收入<span></span></a></li>
        <li class="show_active sonLi5"><a href="/finance/wholesale" id="show_url_list" class="show_url">气站批发收入<span></span></a></li>
        <li class="show_active sonLi5"><a href="/spending/wholesale" id="show_url_list" class="show_url">其它收入<span></span></a></li>
        <li class="show_active sonLi5"><a href="/spending/procurement" id="show_url_list" class="show_url">气站采购支出<span></span></a></li>
        <li class="show_active sonLi5"><a href="/spending/oprocurement" id="show_url_list" class="show_url">其它支出<span></span></a></li>
        <li class="show_active sonLi5"><a href="/shop/payment" id="show_url_list" class="show_url">门店预付款<span></span></a></li>
        <li class="show_active sonLi5"><a href="/spending/detect" id="show_url_list" class="show_url">钢瓶年检支出<span></span></a></li>
        <li class="show_active sonLi5"><a href="/spending/service" id="show_url_list" class="show_url">钢瓶维修支出<span></span></a></li>
    </ul>
    <ul index="5" style="display:none;">
        <li class="show_active sonLi5"><a href="/filling/index" id="show_url_list" class="show_url">门店配送计划单<span></span></a></li>
        <li class="show_active sonLi5"><a href="/filling/records" id="show_url_list" class="show_url">气站充装计划单<span></span></a></li>
        <li class="show_active sonLi11"><a href="/filling/czlist" id="show_url_list" class="show_url">充装数据同步<span></span></a></li>
        <li class="show_active sonLi5"><a href="/filling/delivery" id="show_url_list" class="show_url">气站配送出库单<span></span></a></li>  
        <li class="show_active sonLi5"><a href="/filling/confirme" id="show_url_list" class="show_url">门店入库确认单<span></span></a></li>
        <li class="show_active sonLi5"><a href="/filling/confirmback" id="show_url_list" class="show_url">配送回库确认单<span></span></a></li>
        <li class="show_active sonLi5"><a href="/gastj/planlist" id="show_url_list" class="show_url">燃气采购计划单<span></span></a></li>
        <li class="show_active sonLi5"><a href="/instock/purchase" id="show_url_list" class="show_url">钢瓶采购计划单<span></span></a></li>
        <li class="show_active sonLi5"><a href="/instock/index" id="show_url_list" class="show_url">配件采购计划单<span></span></a></li>
        <li class="show_active sonLi5"><a href="/supplier/index" id="show_url_list" class="show_url">供应商管理<span></span></a></li>
        <li class="show_active sonLi5"><a href="/gasinout/index" id="show_url_list" class="show_url">燃气库存<span></span></a></li>
        <li class="show_active sonLi5"><a href="/filling/czbottle" id="show_url_list" class="show_url">钢瓶初始化<span></span></a></li>
    </ul>
    <ul index="6" style="display:none;">
        <li class="show_active sonLi3"><a href="/authrule/index" id="show_url_list" class="show_url">规则管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/org/index" id="show_url_list" class="show_url">部门管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/authrole/index" id="show_url_list" class="show_url">角色管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/quarters/index" id="show_url_list" class="show_url">岗位管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/authrule/app" id="show_url_list" class="show_url">app规则管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/authrole/app" id="show_url_list" class="show_url">app角色权限<span></span></a></li>
        <li class="show_active sonLi3"><a href="/regionmanage/index" id="show_url_list" class="show_url">区域管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/commodity/index" id="show_url_list" class="show_url">商品种类管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/bottlestatus/index" id="show_url_list" class="show_url">钢瓶状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/bottletype/index" id="show_url_list" class="show_url">钢瓶类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/cylinderdeposit/index" id="show_url_list" class="show_url">钢瓶押金设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/producttype/index" id="show_url_list" class="show_url">配件规格设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/ordertype/index" id="show_url_list" class="show_url">订单类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/orderstatus/index" id="show_url_list" class="show_url">订单状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/orderevaluation/index" id="show_url_list" class="show_url">订单评价设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/customersource/index" id="show_url_list" class="show_url">客户来源设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/customertype/index" id="show_url_list" class="show_url">客户类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/customerstatus/index" id="show_url_list" class="show_url">客户状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/storetype/index" id="show_url_list" class="show_url">门店类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/storerating/index" id="show_url_list" class="show_url">门店等级设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/storestatus/index" id="show_url_list" class="show_url">门店状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/applicationtype/index" id="show_url_list" class="show_url">申请类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/approvalstatus/index" id="show_url_list" class="show_url">审批状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/peoplestate/index" id="show_url_list" class="show_url">人员状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/rolestate/index" id="show_url_list" class="show_url">角色状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/quarterstate/index" id="show_url_list" class="show_url">岗位状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/prepaystate/index" id="show_url_list" class="show_url">预付款状态设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/payproject/index" id="show_url_list" class="show_url">支出项目设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/revenueproject/index" id="show_url_list" class="show_url">收入项目设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/gas/index" id="show_url_list" class="show_url">燃气类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/tank/index" id="show_url_list" class="show_url">储罐类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/repair/index" id="show_url_list" class="show_url">报修类型设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/tousu/list" id="show_url_list" class="show_url">投诉类型管理<span></span></a></li>
        <li class="show_active sonLi3"><a href="/report/index" id="show_url_list" class="show_url">安全报告设置<span></span></a></li>
        <li class="show_active sonLi3"><a href="/syslog/index" id="show_url_list" class="show_url">登陆日志<span></span></a></li>
        <li class="show_active sonLi3"><a href="/manufacturer/index" id="show_url_list" class="show_url">生产厂家设置<span></span></a></li>
        <li class="show_active sonLi5"><a href="/commodityprice/index" id="show_url_list" class="show_url">商品价格管理<span></span></a></li>
    </ul>
</div>