<div id="header" class="mb20">
    <div class="w1170">
        <h1 class="fl">
            <img src="/statics/newhome/images/logo.png" />
        </h1>
        <div class="nav fl">
            <a href="javascript:;" class="active">运营简报</a>
            <a href="javascript:;">运营管理</a>
            <a href="javascript:;">销售</a>
            <a href="javascript:;">财务</a>
            <a href="javascript:;">生产</a>
            <a href="javascript:;">设置</a>
        </div>
        <div class="fr user"> 
            {if $smarty.session.userinfo neq ''}
            <a href="/my/home/index">{$smarty.session.userinfo.username}</a>
            <span>|</span>
            <a href="/my/passport/logout">退出</a>
            {else}
            <a href="/index/userlogin">登陆</a>
            {/if}
        </div>
    </div>
</div>