<div class="contNav">
    <ul class="clearfix">
        <li class="navLi1">
            <a href="javascript:;">运营简报<span></span></a>
        </li>
        <li class="navLi2">
            <a href="javascript:;">运营管理<span></span></a>
        </li>
        <li class="navLi3">
            <a href="javascript:;">销售管理<span></span></a>
        </li>
        <li class="navLi4">
            <a href="javascript:;">财务管理<span></span></a>
        </li>
        <li class="navLi5">
            <a href="javascript:;">生产管理<span></span></a>
        </li>
        <li class="navLi6">
            <a href="javascript:;">设置管理<span></span></a>
        </li>
    </ul>
</div>