{extends file='ztemp/main.phtml'}
{block name=title}配件规格管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        配件规格管理
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST" action="/producttype/add">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">规格名称：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="name" value="{$name}" style="width:200px;">
                        <span>规格名称</span>
                    </div>
                </div>
            </div>
            <div class="rqLine">
                <div class="rqOption clearfix">
                    <label class="fl">备注:</label>
                    <div class="fl">
                        <textarea name="comment" id="comment">{$comment}</textarea>
                        <div class="rqLine">
                            <div class="rqOption fl">
                                <a href="javascript:document.form.submit();" class="blueBtn">保存</a>
                            </div>
                            <div class="rqOption fl">
                                <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="id" value="{$id}" id="updateID">
        </form>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/other.js"></script>{/block}