{extends file='main_other.phtml'}
{block name=body}
<div class="content">
    <div class="yzbox">
        <h2>重置密码</h2>
        <div class="inputBox placeholder">
            <input type="password" style="width:378px;">
            <span>设置新密码</span>
        </div>
        <div class="inputBox placeholder">
            <input type="password" style="width:378px;">
            <span>再次输入新密码</span>
        </div>
        <a href="javascript:;" class="blueBtn4">确认</a>
    </div>
</div>
{/block}