{extends file='ztemp/main.phtml'}
{block name=title}规则管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        规则管理
        <span></span>
    </div>
    <div class="contRList">
    <form name="form" method="POST" action="/org/add">
        <div class="rqLine clearfix">
            <div class="rqOption fl">
                <label class="fl">部门：</label>
                <div class="inputBox fl placeholder">
                    <input type="text" name="org_name" value="{$org_name}" style="width:200px;">
                    <span>部门名称</span>
                </div>
            </div>
        </div>
        <div class="rqLine clearfix">
            <div class="rqOption fl">
                <label class="fl">备注：</label>
                <div class="inputBox fl placeholder">
                    <textarea name="org_content" id="comment">{$org_content}</textarea>
                    <span>备注</span>
                </div>
            </div>
        </div>
        <div class="rqLine">
            <div class="rqOption clearfix">
                <label class="fl">上级部门：</label>
                <div class="selectBox fl" style="width:172px;">
                    <div class="mySelect">
                        <select name="org_parent_id" id="org_parent_id" class="selectmenu"style="width:200px" >
                            <option value="0">请选择上级</option>
                            {if $orgData neq ''}
                            {foreach $orgData as $value}
                            {if $org_parent_id == $value['org_id']}
                            <option value="{$value['org_id']}" selected="selected">{$value['org_name']}</option>
                            {else}
                            <option value="{$value['org_id']}">{$value['org_name']}</option>
                            {/if}
                            {/foreach}
                            {/if}
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="rqLine clearfix">
            <div class="rqOption fl">
                <label class="fl">排序：</label>
                <div class="inputBox fl placeholder">
                    <input type="text" name="listorder" id="list_sort" value="{$listorder}" style="width:200px;">
                    <span>输入标记</span>
                </div>
            </div>
        </div>
        <div class="rqLine">
            <div class="rqOption clearfix">
                <label class="fl"></label>
                <div class="fl">
                    <div class="rqLine">
                        <div class="rqOption fl">
                            <a href="javascript:;" onclick="change_menu()" class="blueBtn">保存</a>
                        </div>
                        <div class="rqOption fl">
                            <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" name="org_id" value="{$org_id}" id="updateID">
    </form>
</div>
</div>
<script type="text/javascript">
    function change_menu() {
        var menu_type = $('#org_parent_id').find('option:selected');
        var id = parseInt($('#updateID').val());
        if (id < 1) {
            $('#listorder').val(menu_type.attr('list_sort') + $('#listorder').val());
        }
        document.form.submit();
    }
</script>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/other.js"></script>{/block}