<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=no;">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="format-detection" content="telephone=no">

<title>跳转提示</title>
<style type="text/css">
*{ padding: 0; margin: 0;}
body{ background: #fff; font-family: '微软雅黑'; color: #333; font-size: 16px; }
.system-message{ padding: 24px 0px; width:95%;margin:0px auto;text-align:center;}
.system-message h1{ font-size: 100px; font-weight: normal; line-height: 120px; margin-bottom: 12px; }
.system-message .jump{ padding-top: 10px}
.system-message .jump a{ color: #333;}
.system-message .success,.system-message .error{ line-height: 1.8em; font-size: 16px }
.system-message .success { padding:5px; font-size:18px; border-radius:5px; }
.system-message .error { padding:5px;font-size:18px;color:#E54C00;border-radius:5px; }
.system-message .detail{ font-size: 12px; line-height: 20px; margin-top: 12px; display:none }
</style>
</head>
<body>
<div class="system-message">
{if $message}
<p class="success"><img src="{$_PUBLIC}/upload/photo/touxiang.jpg" alt="" style="height:120px;" /><br/>{$message}</p>
{else}
<p class="error"><img src="{$_PUBLIC}/upload/photo/touxiang.jpg" alt="" style="height:120px;" /><br/> {$error}</p>
{/if}
<p class="detail"></p>
<p class="jump">
页面自动 <a id="href" href="{$jumpUrl}">跳转</a> 等待时间： <b id="wait">{$waitSecond}</b>
</p>
</div>
<script type="text/javascript">
(function(){
var wait = document.getElementById('wait'),href = document.getElementById('href').href;
var interval = setInterval(function(){
	var time = --wait.innerHTML;
	if(time <= 0) {
		location.href = href;
		clearInterval(interval);
	};
}, 1000);
})();
</script>
</body>
</html>
