{extends file='ztemp/main.phtml'}
{block name=title}钢瓶年检支出{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        钢瓶年检支出
        <span></span>
    </div>
    <div class="contRList">
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>规格</th>
                        <th>年检数量</th>
                        <th>年检费用</th>
                        <th>支出金额</th>
                        <th>合计</th>
                    </tr>
                </thead>
                <tbody>
                    {if $allData neq ''}
                    {foreach $allData as $akey => $val}
                    <tr>
                        <td>{$val['goods_name']}</td>
                        <td>{$val['total']}</td>
                        <td>{$val['goods_price']}</td>
                        <td>{$val['money']}</td>
                        {if $akey eq 0}
                        <td rowspan="{count($allData)}"></td>
                        {/if}
                    </tr>
                    {/foreach}
                    {else}
                    <tr>
                        <td colspan="5">暂时没有数据</td>
                    </tr>
                    {/if}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="contRItem">
    <div class="contRTitle">
        年检支出记录
        <span></span>
        <a href="javascript:;" class="blueBtn8 addNjzc">添加年检支出</a>
    </div>
    <div class="contRList">
        <form name="form" method="POST">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">单号：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="ds_no" value="{$param['ds_no']}" style="width:158px;">
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">年检时间：</label>
                    <div class="riliInputBox fl">
                        <div class="riliInput fl">
                            <input type="text" style="width:150px;" id="time_start" name="start_time" value="{$param['start_time']}">
                        </div>
                        <span class="fl">至</span>
                        <div class="riliInput fl">
                            <input type="text" id="time_end" style="width:150px;" name="end_time" value="{$param['end_time']}">
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                    <input type="submit" name="submit" class="blueBtn" value="搜索" />
                </div>
            </div>
        </form>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>单号</th>
                        <th>送检厂家</th>
                        <th>规格</th>
                        <th>数量</th>
                        <th>检测费</th>
                        <th>金额</th>
                        <th>经办人</th>
                        <th>年检时间</th>
                    </tr>
                </thead>
                <tbody>
                    {if $list neq ''}
                    {$list}
                    {else}
                    <tr><td colspan="8">暂时没有数据</td></tr>
                    {/if}
                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$param['page']}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/nianjianzhichu.js"></script>{/block}