{extends file='ztemp/main.phtml'}
{block name=title}库存警戒线管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        库存警戒线管理
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST" action="/baseline/add">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">警戒线数：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="num" value="{$num}" style="width:150px;">
                        <span>警戒线数</span>
                    </div>
                </div>
            </div>
            {if empty($id)}
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">报警产品类型：</label>
                    <div class="selectBox fl" style="width:172px;">
                        <div class="mySelect">
                            <select name="type" id="typelist" class="selectmenu">
                                <option value="0" >请选择</option>
                                {foreach $typeObject as $k => $v}
                                <option value="{$k}" {if $type eq $k}selected="selected"{/if}>{$v}</option>
                                {/foreach}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="rqOption fl">
                    <label class="fl">产品类别：</label>
                    <div class="selectBox fl" style="width:172px;">
                        <div class="mySelect">
                            <select name="goods_type" id="goods_type" class="selectmenu">
                                <option value="0" >请选择</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            {else}
            <input type="hidden" name="type" value="{$type}" />
            {/if}
            <div class="rqLine clearfix">
                <div class="rqOption clearfix">
                    <label class="fl">备注：</label>
                    <div class="fl">
                        <textarea name="comment">{$comment}</textarea>
                        <div  class="rqLine">
                            <div class="rqOption fl">
                                <a href="javascript:document.form.submit();" class="blueBtn">提交</a>
                            </div>
                            <div class="rqOption fl">
                                <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="id" value="{$id}" />
        </form>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/other.js"></script>{/block}