{extends file='ztemp/main.phtml'}
{block name=title}投诉类型管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        投诉类型管理
        <span></span>
        <a href="/tousu/addtype" class="blueBtn8 addShangpin">添加投诉类型</a>
    </div>
    <div class="contRList">
        <div class="rqTabItem">
            <table>
                <tr>
                    <td>编号</td>
                    <td>类型</td>
                    <td>备注</td>
                    <td>操作</td>
                </tr>
                {if $list neq ''}
                {foreach $list as $value}
                <tr>
                    <td>{$value['toususn']}</td>
                    <td>{$value['title']}</td>
                    <td>{$value['comment']}</td>
                    <td>
                        <a href="/tousu/editetype?id={$value['id']}">修改</a>|
                        <a href="/tousu/deltype?id={$value['id']}" onclick="if(confirm('确定删除?')==false)return false;">删除</a>
                    </td>
                </tr>
                {/foreach} 
                {else}
                <tr><td colspan="4">暂时没有数据</td></tr>
                {/if}
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$count}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$param['page']}">
            <input type="hidden" class="totalPage" value="{ceil($count/15)}">
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/shangpinzhongleiManage.js"></script>{/block}