{extends file='layouts\main.phtml'}
{block name=body}

<div class="content clearfix">
    {include file='layouts\left.phtml'}
    <div class="fr" style="width:904px;">
        <div class="contRItem">
            <div class="contRTitle">
                押金记录
                <span></span>
            </div>
            <div class="contRList">
                <form name="form" method="POST" action="/my/home/backbottle">
                    <div class="rqLine">
                        <div class="rqOption clearfix">
                            <label class="fl">退瓶备注：</label>
                            <textarea class="fl" style="height:100px;" name="comment"></textarea>
                        </div>
                    </div>
                    <div class="rqLine rqLineBtn">
                        <div class="rqOption">
                            <a href="javascript:if(confirm('确定提交？')){ document.form.submit(); }" class="blueBtn">提交退瓶</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="contRItem">
            <div class="contRTitle">
                退瓶记录
                <span></span>
                <p>共 <font>{$ext['count']}</font> 条记录</p>
            </div>
            <div class="contRList">
                <div class="rqTabItem">
                    <table>
                        <thead>
                            <tr>
                                <th>编号</th>
                                <th>日期</th>
                                <th>备注</th>
                            </tr>
                        </thead>
                        <tbody>
                            {if count($ext['list']) > 0}
                            {foreach $ext['list'] as $value}
                            <tr>
                                <td>{$value['depositsn']}</td>
                                <td>{$value['time']}</td>
                                <td>{$value['comment']}</td>
                            </tr>
                            {/foreach}
                            {else}
                            <tr>
                                <td colspan="3">暂时没有数据</td>
                            </tr>
                            {/if}
                        </tbody>
                    </table>
                </div>
                <div class="table-pages pageNav clearfix" id="pageNav">	</div>
            </div>
        </div>
    </div>
</div>
</div>
<script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
{/block}