{extends file='layouts\main.phtml'}
{block name=body}
<div class="content clearfix">
    {include file='layouts\left.phtml'}
    <div class="fr" style="width:904px;">
        <div class="contRItem">
            <div class="contRTitle">
                订单查询
                <span></span>
            </div>
            <form name="form" method="POST">
                <div class="contRList">
                    <div class="rqLine clearfix">
                        <div class="rqOption fl">
                            <label class="fl">订单编号：</label>
                            <div class="inputBox fl">
                                <input type="text" name="order_sn" value="{$param['order_sn']}" style="width:190px;">
                            </div>
                        </div>
                    </div>
                    <div  class="rqLine clearfix">
                        <div class="rqOption fl">
                            <label class="fl">时间：</label>
                            <div class="riliInputBox fl">
                                <div class="riliInput fl">
                                    <input type="text" style="width:150px;" name="start_time" value="{$param['start_time']}" id="time_start">
                                </div>
                                <span class="fl">至</span>
                                <div class="riliInput fl">
                                    <input type="text" id="time_end" name="end_time" value="{$param['end_time']}" style="width:150px;">
                                </div>
                            </div>
                        </div>
                        <div class="rqOption fl">
                            <input type="hidden" name="page" value="{if $post['page']}{$post['page']}{else}1{/if}">
                            <a href="javascript:if(confirm('确定提交？')){ document.form.submit(); }" class="blueBtn">搜索</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="contRItem">
            <div class="contRTitle">
                历史订单记录
                <span></span>
            </div>
            <div class="contRList">
                <div class="rqTabItem">
                    <table>
                        <thead>
                            <tr>
                                <th>订单号</th>
                                <th>运送费</th>
                                <th>送气工</th>
                                <th>送气工电话</th>
                                <th>总金额</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {if $data['ext']['list'] neq ''}
                            {foreach $data['ext']['list'] as $value}
                            <tr>
                                <td>{$value['order_sn']}</td>
                                <td>{$value['shipment']}</td>
                                <td>{$value['shipper_name']}</td>
                                <td>{$value['shipper_mobile']}</td>
                                <td>{$value['money']}</td>
                                <td class="tableBtn">
                                    <a href="javascript:;">投诉</a>
                                    <span>|</span>
                                    <a href="javascript:;">评价</a>
                                </td>
                            </tr>
                            {/foreach}
                            {/if}
                        </tbody>
                    </table>
                </div>
                <div class="table-pages pageNav clearfix" id="pageNav">	</div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var page = {$data['page']}
    var totalPage = {$data['ext']['count']};
</script>
<script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
{/block}