{extends file='layouts\main.phtml'}
{block name=body}
<div class="content clearfix">
    {include file='layouts\left.phtml'}
    <div class="fr" style="width:904px;">
        <div class="contRItem">
            <div class="contRTitle">
                我要投诉
                <span></span>
            </div>
            <form name="form" method="POST" action="/my/home/tousu">
            <div class="contRList tousu">
                <div class="rqLine mycheckList">
                    <div class="rqOption clearfix mycheckbox">
                        <label class="fl">投诉原因：</label>
                        <div class="checkList fl">
                            {if $tousuData neq ''}
                            {foreach $tousuData as $rVal}
                            <input type="checkbox" name="tousuType[]" value="{$rVal['id']}" />{$rVal['title']}
                            {/foreach}
                            {/if}
                        </div>
                    </div>
                </div>
                <div class="rqLine">
                    <div class="rqOption clearfix">
                        <label class="fl">投诉备注：</label>
                        <textarea class="fl" style="height:100px;" name="comment"></textarea>
                    </div>
                </div>
                <div class="rqLine rqLineBtn">
                    <div class="rqOption">
                        <a href="javascript:document.form.submit();" class="blueBtn">提交诉讼</a>
                    </div>
                </div>
            </div>
            </form>
        </div>
        <div class="contRItem">
            <div class="contRTitle">
                诉讼记录
                <span></span>
                <p>共 <font>{$ext['count']}</font> 条记录</p>
            </div>
            <div class="contRList">
                <div class="rqTabItem">
                    <table>
                        <thead>
                            <tr>
                                <th>编号</th>
                                <th>诉讼时间</th>
                                <th class="w200">诉讼内容</th>
                                <th>应答人</th>
                                <th>解决与否</th>
                                <th class="w150">客户评价</th>
                            </tr>
                        </thead>
                        <tbody>
                            {if count($ext['list']) > 0}
                            {foreach $ext['list'] as $value}
                            <tr>
                                <td>{$value['encode_id']}</td>
                                <td>{date('Y/m/d',$value['ctime'])}</td>
                                <td>{$value['comment']}</td>
                                <td>{$value['admin_user_name']}</td>
                                <td>{if $value['status'] eq 1}已处理{else}未处理{/if}</td>
                                <td class="tableBtn">
                                    <a href="javascript:;">评价</a>
                                </td>
                            </tr>
                            {/foreach}
                            {else}
                            <tr><td colspan="7">暂时还没有数据</td></tr>
                            {/if}
                        </tbody>
                    </table>
                </div>
                <div class="table-pages pageNav clearfix" id="pageNav">	</div>
            </div>
        </div>
    </div>
</div>
{/block}