{extends file='main.phtml'}
{block name=rtitle}充装统计{/block}
{block name=operate}
<div class="operateBtn">
    <a href="/statistics/fillingtype">按照类型统计</a>
    <font>|</font>
    <a href="/statistics/filling">充装统计</a>
</div>
{/block}
{block name=body}
{literal}
<script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
<script>
    $(function () {
        $('#container').highcharts({
            title: {
                text: '充装统计',
                x: -20 //center
            },
            subtitle: {
                text: 'Source: WorldClimate.com',
                x: -20
            },
            xAxis: {
                categories: {/literal}{$title}{literal}
            },
            yAxis: {
                title: {
                    text: 'Temperature (个)'
                },
                plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
            },
            tooltip: {
                valueSuffix: '个'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: {/literal}{$show}{literal}
        });
    });
</script>
{/literal}
<div id="container" style="min-width:700px;height:400px"></div>
<div class="orderList contRList">
    <form name="form" method="POST">
        <div class="rqLine clearfix">
            <div class="rqOption fl">
                <label class="fl">时间：</label>
                <div class="riliInputBox fl">
                    <div class="riliInput fl">
                        <input type="text" style="width:150px;" name="start_time" id="time_start">
                    </div>
                    <span class="fl">至</span>
                    <div class="riliInput fl">
                        <input type="text" id="time_end" name="end_time" style="width:150px;">
                    </div>
                </div>
            </div>
        </div>
        <div class="rqLine clearfix">
            <div class="rqOption fr">
                <a href="javascript:document.form.submit();" class="blueBtn">搜索</a>
            </div>
        </div>
    </form>
    <table>
        <tr>
            <td>充装类型</td>
            <td>充装数量</td>
        </tr>

        {if $data neq ''}
        {foreach $data as $value}
        <tr>
            <td>{$value['name']}</td>
            <td>{$value['total']}</td>
        </tr>
        {/foreach} 
        {/if}

    </table>
</div>
{/block}