{extends file='ztemp/main.phtml'}
{block name=title}送气工统计{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        送气工统计
        <span></span>
    </div>
    <div class="contRList">
        {literal}
        <script type="text/javascript" src="/statics/js/jquery.min.js"></script>
        <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
        <script>
            $(function () {
                var categories_text = {/literal}{$categories}{literal};
                var series_text = {/literal}{$series}{literal};
                $('#container').highcharts({
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: '送气工订单量统计',
                        x: -20 //center
                    },
                    subtitle: {
                        text: '截止当前送气工订单量统计',
                        x: -20
                    },
                    credits:{
                                enabled:false // 禁用版权信息
                            },
                    xAxis: {
                        //categories: ["李二狗","王二蛋","赵小毛","吴三水","王红","李丹","赵四","宋茜","李湘","唐嫣"]
                        categories: categories_text
                    },
                    yAxis: {
                        title: {
                            text: '(个)'
                        },
                        plotLines: [{
                                value: 0,
                                width: 1,
                                color: '#808080'
                            }]
                    },
                    tooltip: {
                        valueSuffix: '个'
                    },
                    legend: {
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'middle',
                        borderWidth: 0
                    },
                    //series: [{"name":"订单量","data":[94,89,86,80,78,70,69,68,67,65]}]
                    series: [{"name":"订单量","data":series_text}]
                });
            });
        </script>
        {/literal}
        <div id="container"></div>
    </div>
</div>
<div class="contRItem">
    <div class="contRTitle">
        送气工统计记录
        <span></span>
    </div>
    <div class="contRList">
        <div class="rqLine clearfix">
            <form name="form" method="POST">
                <div class="rqOption3 fl">
                    <label class="fl">选择门店：</label>
                    <div class="selectBox fl">
                        <div class="mySelect">
                            <select name="shop_id" class="selectmenu" style="width:170px;">
                                <option value="">选择站点</option>
                                {foreach $shopObject as $k=>$v}
                                {if $k eq $param['shop_id']}
                                <option value="{$k}" selected="selected">{$v['shop_name']}</option>
                                {else}
                                <option value="{$k}">{$v['shop_name']}</option>
                                {/if}
                                {/foreach}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="rqOption3 fl">
                    <label class="fl">送气工名称：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="shipper_name" id="shipper_id" value="{$param['shipper_name']}" style="width:130px;">
                    </div>
                </div>
                <div class="rqOption fl">
                    <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                    <input type="submit" name="submit" class="blueBtn" value="搜索" />
                </div>
            </form>
        </div>
        <div class="rqTabItem">
            <table>
                <thead>
                    <tr>
                        <th>隶属门店</th>
                        <th>送气工姓名</th>
                        <th>订单数量</th>
                    </tr>
                </thead>
                <tbody>
                    {if $ext['list'] neq ''}
                    {foreach $ext['list'] as $value}
                    <tr>
                        <td>{$shopObject[$value['shop_id']]['shop_name']}</td>
                        <td class="tableBtn"><a href="javascript:;">{$value['shipper_name']}</a></td>
                        <td>{$value['order_no']}</td>
                    </tr>
                    {/foreach}
                    {else}
                    <tr><td colspan="3">暂时还没有数据</td></tr>
                    {/if}
                </tbody>
            </table>
        </div>
        <div class="clearfix sqspBottom">
            <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
            <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
            <input type="hidden" class="currentPage" value="{$page}">
            <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
            <input type="hidden" class="paramlist" value="{$getparamlist}" />
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/songqigongtongji.js"></script>{/block}