{extends file='main.phtml'}
{block name=rtitle}订单统计{/block}
{block name=operate}<a href="/statistics/warehoustype">按照配件类型统计</a>{/block}
{block name=body}
{literal}
<script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
<script>
    $(function () {
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: '配件库存'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [{
                    type: 'pie',
                    name: '所占比重',
                    /*data: [
                        ['Firefox', 45.0],
                        ['IE', 26.8],
                        {
                            name: 'Chrome',
                            y: 12.8,
                            sliced: true,
                            selected: true
                        },
                        ['Safari', 8.5],
                        ['Opera', 6.2],
                        ['Others', 0.7]
                    ]*/
                    data:{/literal}{$json_data}{literal}
                }]
        });
    });
</script>
{/literal}
<div id="container" style="min-width:700px;height:400px"></div>
<div class="orderList contRList">
    <form name="form" method="POST">
        <div class="rqLine clearfix">
            <div class="rqOption fl">
                <label class="fl">时间：</label>
                <div class="riliInputBox fl">
                    <div class="riliInput fl">
                        <input type="text" style="width:150px;" name="start_time" id="time_start">
                    </div>
                    <span class="fl">至</span>
                    <div class="riliInput fl">
                        <input type="text" id="time_end" name="end_time" style="width:150px;">
                    </div>
                </div>
            </div>
            <div class="rqOption fl">
                <label class="fl">门店列表：</label>
                <div class="selectBox fl" style="width:172px;">
                    <div class="mySelect">
                        <select name="shop_id" class="selectmenu">
                            <option value="0">请选择</option>
                            {foreach $shopObject as $k=>$v}
                            <option value="{$k}">{$v['shop_name']}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="rqLine clearfix">
            <div class="rqOption fr">
                <a href="javascript:document.form.submit();" class="blueBtn">搜索</a>
            </div>
        </div>
    </form>
    <table>
        <tr>
            <td>门店名称</td>
            <td>配件数量</td>
        </tr>

        {if $data neq ''}
        {foreach $data as $value}
        <tr>
            <td>{$shopObject[$value['shop_id']]['shop_name']}</td>
            <td>{$value['total']}</td>
        </tr>
        {/foreach} 
        {/if}

    </table>
</div>
{/block}