{extends file='ztemp/main.phtml'}
{block name=title}消息通知{/block}
{block name=head}
{literal}
<script type="text/javascript" src="/statics/js/jquery.min.js"></script>
<script type="text/javascript" src="/statics/js/jquery-ui.js"></script>
<script type="text/javascript" src="/statics/js/datepicker-zh-CN.js"></script>
<script type="text/javascript" src="/statics/js/pages.js"></script>

<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        消息管理
        <span></span>
    </div>
    <div class="contRList">
        <div class="path">
            <a href="/news/index">消息列表</a>&nbsp;
            <i></i>&nbsp;
            <a href="javascript:void(0);" class="active">消息详情</a>
        </div>
        <div class="mesgDetail">
            <h3>{$message_title}</h3>
            <div class="mesgBottom">
                <span>发布部门：<font>办公室</font></span>&nbsp;
                <span>发布人：<a href="javascript:void(0);">{$admin_user}</a></span>&nbsp;
                <span>接收对象：<font>全部</font></span>&nbsp;
                <span>{date('Y-m-d',$time_created)}</span>
            </div>
            <p> {$message_content}</p>
        </div>
    </div>
</div>
<script type="text/javascript" src="/statics/js/controllers/messageInform.js"></script>
{/block}