<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>瑞气科技</title>
        <link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/style.css">
        <link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/base/jquery-ui.css">
        <script type="text/javascript" src="{$_PUBLIC}/js/jquery.min.js"></script>
        <script type="text/javascript" src="{$_PUBLIC}/js/jquery-ui.js"></script>
        <script type="text/javascript" src="{$_PUBLIC}/js/jquery.cookie.js"></script>
    </head>
    <body>
        <div class="wrap">
            {include file='staticpage_header_other.phtml'}
            {block name=body}{/block}
            {include file='staticpage_footer.phtml'}
        </div>
        <script type="text/javascript" src="{$_PUBLIC}/js/common.js"></script>
    </body>
</html>