<div class="bottom clearfix">
    <div class="fl leftTxt">
        <a href="#">服务协议</a><br>
        <a href="#">公司公告</a><br>
        <a href="#">服务协议</a><br>
        <a href="#">关于我们</a><br>
        <a href="#">联系我们</a>
    </div>
    <ul class="fl saoma">
        <li>
            <div class="code">
                <img src="/statics/upload/custom.png">
            </div>	
            <p>客户端APP</p>
            <p>扫一扫关注</p>    
        </li>
        <li>
            <div class="code">
                <img src="/statics/upload/shipper.png">
            </div>	
            <p>送气工端APP</p>
            <p>扫一扫下载</p>    
        </li>
        <li>
            <div class="code">
                <img src="/statics/upload/general.png">
            </div>	
            <p>管理端APP</p>
            <p>扫一扫下载</p>    
        </li>
    </ul>
    <dl class="fl">
        <dt>行业动态</dt>
        <dd><a href="#">河北沧州智能燃气平台已开通！</a></dd>
        <dd><a href="#">智慧燃气App 2.0发布！</a></dd>
        <dd><a href="#">交易量突破1000KG！</a></dd>
    </dl>
    <dl class="fr">
        <dt>安全常识</dt>
        <dd><a href="#">液化石油气安全使用常识</a></dd>
        <dd><a href="#">安全使用液化气的方法</a></dd>
        <dd><a href="#">安全使用液化气的消防安全知识</a></dd>
        <dd><a href="#">液化气站安全距离</a></dd>
    </dl>
</div>