<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="renderer" content="webkit">
        <title>瑞气科技</title>
        <link rel="stylesheet" type="text/css" href="/statics/newhome/css/style.css">
        <script type="text/javascript" src="/statics/js/require.min.js"></script>
    </head>
    <body>
        <div class="wrap">
            {include file='main_new_header.phtml'}
            {block name=body}{/block}
            {include file='main_new_footer.phtml'}
        </div>
        <script type="text/javascript" src="/statics/js/controllers/indexCtrl.js"></script>
    </body>
</html>