<div class="fl" style="width:183px;">
    <div class="contRItem">
        <div class="iconTitle clearfix">
            <h3 class="fl">个人中心</h3>
        </div>
        <div class="personalCenter">
            <div class="myheadface">
                <img src="{$_PUBLIC}/upload/photo/touxiang.jpg">
            </div>
            <ul>
                <li class="myname">{$username}</li>
                <li><span></span>{$mobile_phone}</li>
                <!--li class="myaddress"><span></span>北京市  朝阳区</li>
                <li class="mybalance"><span></span>余额：<font>155元<font></li-->
            </ul>
            <!--a href="javascript:;" class="blueBtn4">充值</a-->
        </div>
    </div>
    <div class="contLeft fl operateList">
        <ul style="display:block;">
            <li class="dq_li6 active">
                <a href="/personal/index">个人资料<span></span></a>
            </li>
        </ul>
    </div>
</div>