<link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/style.css">
<link rel="stylesheet" type="text/css" href="{$_PUBLIC}/css/base/jquery-ui.css">
<script type="text/javascript" src="{$_PUBLIC}/js/jquery.min.js"></script>
<script type="text/javascript" src="{$_PUBLIC}/js/jquery-ui.js"></script>
<script type="text/javascript" src="{$_PUBLIC}/js/datepicker-zh-CN.js"></script>
<script type="text/javascript" src="{$_PUBLIC}/js/pages.js"></script>