{extends file='ztemp/main.phtml'}
{block name=title}回流率-简报{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
	<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        回流率统计
        <span></span>
    </div>
    <div class="contRList">
        <div class="rq_data">
            <ul class="clearfix">
                <li class="rq_down dataLi4">
                    <p>回流率</p>
                    <span class="rq_num"><strong>100%</strong></span>
                    <font>100</font>
                    <span class="percent">%</span>
                    <i></i>
                </li>
                <li class="rq_up dataLi5">
                    <p>回流率</p>
                    <span class="rq_num"><strong>100%</strong></span>
                    <font>100</font>
                    <span class="percent">%</span>
                    <i></i>
                </li>
                <li class="rq_up dataLi6">
                    <p>回流率</p>
                    <span class="rq_num"><strong>100%</strong></span>
                    <font>100</font>
                    <span class="percent">%</span>
                    <i></i>
                </li>
            </ul>
        </div>
        {literal}
        <script type="text/javascript" src="/statics/js/jquery.min.js"></script>
        <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
        <script>
            $(function(){
                var title = {/literal}{$title}{literal};
                var show = {/literal}{$show}{literal};
                $('#container').highcharts({
		    	chart: {
		            type: 'column'
		        },
		        title: {
		            text: '回流率统计',
		            x: -20 //center
		        },
		        subtitle: {
		            text: '截止当前日期各门店回流率统计',
		            x: -20
		        },
		        credits:{
				    enabled:false // 禁用版权信息
				},
		        xAxis: {
		        	title:'门店名称',
		            categories: title
		        },
		        yAxis: {
		            title: {
		                text: '回流个数'
		            },
		            labels: {
		                formatter: function() {
		                    return this.value +'个'
		                }
		            },
		            plotLines: [{
		                    value: 0,
		                    width: 1,
		                    color: '#808080'
		                }]
		        },
		        tooltip: {
		        	valueDecimals: 2,
		            valueSuffix: '个'
		        },
		        legend: {
		            enabled:false
		        },
		        series: [{"name":"回流率","data":show}]
		    });
            });
        </script>
        {/literal}
        <div id="container"></div>
        <div class="rq_tab">
            <ul class="tabBtnbox clearfix rq_btnbox">
                <li class="tabBtn">本月<span></span></li>
                <li class="tabBtn">本季度<span></span></li>
                <li class="tabBtn">本年度<span></span></li>
            </ul>
            <ul class="tabItembox rq_itembox">
                <li class="tabItem" style="display:block;">
                    <table>
                        <thead>
                            <tr>
                                <th>门店名称</th>
                                <th>钢瓶数量</th>
                                <th>回流率</th>
                            </tr>
                        </thead>
                        <tbody>
                            {if count($rData) > 0}
                            {foreach $rData as $rVal}
                            <tr>
                                <td>{$shopObject[$rVal['shop_id']]['shop_name']}</td>
                                <td>{$rVal['total']}</td>
                                <td>100%</td>
                            </tr>
                            {/foreach}
                            {else}
                            <tr><td colspan="3">暂时还没有数据</td></tr>
                            {/if}
                        </tbody>
                    </table>
                </li>
                <li class="tabItem">
                    <table>
                        <thead>
                            <tr>
                                <th>门店名称</th>
                                <th>钢瓶数量</th>
                                <th>回流率</th>
                            </tr>
                        </thead>
                        <tbody>
                            {if count($rData) > 0}
                            {foreach $rData as $rVal}
                            <tr>
                                <td>{$shopObject[$rVal['shop_id']]['shop_name']}</td>
                                <td>{$rVal['total']}</td>
                                <td>100%</td>
                            </tr>
                            {/foreach}
                            {else}
                            <tr><td colspan="3">暂时还没有数据</td></tr>
                            {/if}
                        </tbody>
                    </table>
                </li>
                <li class="tabItem">
                    <table>
                        <thead>
                            <tr>
                                <th>门店名称</th>
                                <th>钢瓶数量</th>
                                <th>回流率</th>
                            </tr>
                        </thead>
                        <tbody>
                            {if count($rData) > 0}
                            {foreach $rData as $rVal}
                            <tr>
                                <td>{$shopObject[$rVal['shop_id']]['shop_name']}</td>
                                <td>{$rVal['total']}</td>
                                <td>100%</td>
                            </tr>
                            {/foreach}
                            {else}
                            <tr><td colspan="3">暂时还没有数据</td></tr>
                            {/if}
                        </tbody>
                    </table>
                </li>
            </ul>
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/huiliulvjianbao.js"></script>{/block}