{extends file='znewtemp/main.phtml'}
{block name=title}气站门店销售额分类统计{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/znewhome/css/style.css">
<script type="text/javascript" src="/statics/znewhome/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="fr right-cont">
    <!-- 头部 -->
    <div class="clearfix title mb30">
        <div class="fl mr200">
            <h3>公司销售收入</h3>
            <p>销售 > 销售统计</p>
        </div>	
        <div class="fl chooseDate pt16">
            <span class="fl">选择时段：</span>
            <div class="doubleRili fl">
                <input type="text" id="start" style="width:80px;">
            </div>
            <span class="fl plr8">到</span>
            <div class="doubleRili fl">
                <input type="text" id="end" style="width:80px;">
            </div>
            <a href="javascript:void(0);" class="fl">确定</a>
        </div>
    </div>
    <!-- 选项卡-->
    <div class="tabContrl clearfix myDate mb30">
        <a href="javascript:void(0);" class="active">今日</a>
        <a href="javascript:void(0);">本周</a>
        <a href="javascript:void(0);">本月</a>
        <a href="javascript:void(0);">本季度</a>
        <a href="javascript:void(0);">上半年</a>
        <a href="javascript:void(0);">下半年</a>
        <a href="javascript:void(0);">全年</a>
    </div>
    <div class="tabItem">
        <div class="listItem" style="display:block;">
            <!-- 数据统计 -->
            <div class="dataMenu dataMenu2 mb40  pl290 clientManage">
                <div class="bgBtn">
                    <p>销售收入合计</p>
                    <strong>￥198,985</strong>
                </div>
                <ul class="clearfix">
                    <li>
                        <p>自营零售收入</p>
                        <strong>￥45,125</strong>
                    </li>
                    <li>
                        <p>加盟批发收入</p>
                        <strong>￥678,120</strong>
                    </li>
                </ul>	
            </div>
            <div class="clearfix mb34">
                <!-- 燃气 -->
                <div class="table2 table3 fl" style="width:450px;">
                    <table>
                        <thead>
                            <tr class="H34">
                                <th class="borderRight textLeft ">钢瓶规格</th>
                                <th>数量/重量</th>
                                <th>销售金额</th>
                                <th class="textRight">销售均价</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="borderRight">
                                    <strong>5kg</strong>
                                </td>
                                <td>125瓶<br>2.12吨</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/瓶<br>￥2132.28元/吨</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>10kg</strong>
                                </td>
                                <td>125瓶<br>2.12吨</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/瓶<br>￥2132.28元/吨</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>15kg</strong>
                                </td>
                                <td>125瓶<br>2.12吨</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/瓶<br>￥2132.28元/吨</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>50kg</strong>
                                </td>
                                <td>125瓶<br>2.12吨</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/瓶<br>￥2132.28元/吨</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>50KG(液)</strong>
                                </td>
                                <td>125瓶<br>2.12吨</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/瓶<br>￥2132.28元/吨</td>
                            </tr>
                            <tr>
                                <td class="borderRight redColor">
                                    <strong>燃气销售合计</strong>
                                </td>
                                <td class="redColor">125瓶<br>2.12吨</td>
                                <td class="redColor"><strong>￥2655.20</strong></td>
                                <td class="textRight redColor">￥32.28元/瓶<br>￥2132.28元/吨</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- 配件 -->
                <div class="table2 fr table4" style="width:450px;">
                    <table>
                        <thead>
                            <tr class="H34">
                                <th class="borderRight textLeft">配件名称</th>
                                <th>销售数量</th>
                                <th>销售金额</th>
                                <th class="textRight">销售均价</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="borderRight">
                                    <strong>中压阀</strong>
                                </td>
                                <td>121只</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/只</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>低压阀</strong>
                                </td>
                                <td>121只</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/只</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>炉具</strong>
                                </td>
                                <td>121只</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/只</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>胶管</strong>
                                </td>
                                <td>121只</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/只</td>
                            </tr>
                            <tr>
                                <td class="borderRight">
                                    <strong>喉码</strong>
                                </td>
                                <td>121只</td>
                                <td><strong>￥2655.20</strong></td>
                                <td class="textRight">￥32.28元/只</td>
                            </tr>
                            <tr>
                                <td class="borderRight redColor">
                                    <strong>配件销售合计</strong>
                                </td>
                                <td class="redColor">521件</td>
                                <td class="redColor"><strong>￥12655.20</strong></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- 订单明细 -->
            <div class="result mb30">
                <div class="title mb10">
                    <p>销售收入明细：</p>
                </div>
                <div class="table2 mb34">
                    <table>
                        <thead>
                            <tr>
                                <th class="borderRight textLeft" width="180">气库名称 / 类型</th>
                                <th colspan="6" class="borderRight" >销售明细</th>
                                <th colspan="2" class="textLeft">销售金额</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- 自营 -->
                            <tr class="border_none">
                                <td class="borderRight font_15 textLeft" rowspan="4">
                                    <strong>泊头鸿翔气库</strong>
                                    <div class="style">自营</div>
                                </td>
                                <td><strong>5kg</strong></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td><strong>中压阀<strong/></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td class="textLeft" width="94">燃气销售收入：</td>
                                <td width="100" class="textRight"><strong>￥15685.50</strong></td>
                            </tr>
                            <tr class="border_none">
                                <td><strong>10kg</strong></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td><strong>低压阀<strong/></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td class="textLeft">配件销售收入：</td>
                                <td class="textRight"><strong>￥15685.50</strong></td>
                            </tr>
                            <tr class="border_none">
                                <td><strong>15kg</strong></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td><strong>胶管<strong/></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td class="small2 textLeft redColor" rowspan="2">销售金额合计：</td>
                                <td class="small2 redColor textRight" rowspan="2"><strong>￥1225685.50</strong></td>
                            </tr>
                            <tr>
                                <td class="small2"><strong>50kg(液)</strong></td>
                                <td class="small2">45瓶</td>
                                <td class="borderRight small2">￥655</td>
                                <td class="small2"><strong>炉具<strong/></td>
                                <td class="small2">25瓶</td>
                                <td class="borderRight small2">￥655</td>
                            </tr>
                            <!-- 加盟 -->
                            <tr class="border_none">
                                <td class="borderRight font_15 textLeft" rowspan="4">
                                    <strong>泊头鸿翔气库</strong>
                                    <div class="style style_2">加盟</div>
                                </td>
                                <td><strong>5kg</strong></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td><strong>中压阀<strong/></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td class="textLeft">燃气销售收入：</td>
                                <td class="textRight"><strong>￥15685.50</strong></td>
                            </tr>
                            <tr class="border_none">
                                <td><strong>10kg</strong></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td><strong>低压阀<strong/></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td class="textLeft">配件销售收入：</td>
                                <td class="textRight"><strong>￥15685.50</strong></td>
                            </tr>
                            <tr class="border_none">
                                <td><strong>15kg</strong></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td><strong>胶管<strong/></td>
                                <td>25瓶</td>
                                <td class="borderRight">￥655</td>
                                <td class="small2 textLeft redColor" rowspan="2">销售金额合计：</td>
                                <td class="small2 redColor textRight" rowspan="2"><strong>￥25685.50</strong></td>
                            </tr>
                            <tr>
                                <td class="small2"><strong>50kg(液)</strong></td>
                                <td class="small2">45瓶</td>
                                <td class="borderRight small2">￥655</td>
                                <td class="small2"><strong>炉具<strong/></td>
                                <td class="small2">25瓶</td>
                                <td class="borderRight small2">￥655</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="clearfix sqspBottom">
                    <p class="fl">共 <span>223</span> 条记录</p>
                    <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
                    <input type="hidden" class="currentPage" value="1">
                    <input type="hidden" class="totalPage" value="10">
                </div>
            </div>
        </div>
    </div>
</div>
{/block}
{block name=fjs}
<script type="text/javascript" src="/statics/znewhome/js/controllers/comment.js"></script>
<script type="text/javascript" src="/statics/znewhome/js/controllers/gongsixssrCtrl.js"></script>
{/block}