{extends file='ztemp/main.phtml'}
{block name=title}残液（余气）回收规范{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRItem">
    <div class="contRTitle">
        残液（余气）回收规范
        <span></span>
    </div>
    <div class="contRList">
        <form name="form" method="POST" action="/raffinate/addgas">
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">规格：</label>
                    <div class="selectBox fl" style="width:150px;">
                        <select name="bottle_type" class="selectmenu" id="bottle_type">
                            <option value="">规格</option>
                            {if $bottleTypeData neq ''}
                            {foreach $bottleTypeData as $k => $bVal}
                            {if $bottle_type eq $k}
                            <option value="{$k}" selected="selected">{$bVal['bottle_name']}</option>
                            {else}
                            <option value="{$k}">{$bVal['bottle_name']}</option>
                            {/if}
                            {/foreach}
                            {/if}
                        </select>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">退气总量：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="weight" value="{$weight}" value="" style="width:150px;">
                        <span>允许退气总重量</span>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">最小气量：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="down_weight" value="{$down_weight}" value="" style="width:150px;">
                        <span>最小不能低于0.5</span>
                    </div>
                </div>
            </div>
            <div class="rqLine clearfix">
                <div class="rqOption fl">
                    <label class="fl">钢瓶净重：</label>
                    <div class="inputBox fl placeholder">
                        <input type="text" name="net_weight" value="{$net_weight}" value="" style="width:150px;">
                        <span>钢瓶净重</span>
                    </div>
                </div>
            </div>
            <div class="rqLine">
                <div class="rqOption clearfix">
                    <label class="fl"></label>
                    <div class="fl">
                        <div class="rqLine">
                            <div class="rqOption fl">
                                <a href="javascript:document.form.submit();" class="blueBtn">保存</a>
                            </div>
                            <div class="rqOption fl">
                                <a href="javascript:document.form.reset();" class="grayBtn">清除</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/other.js"></script>{/block}