{extends file='main.phtml'}
{block name=rtitle}安检类型设置{/block}{block name=operate}
<a href="/security/add">添加安检类型</a>
{/block}

{block name=body}
<div class="orderList contRList">
    <table>
        <tr>
            <td>编号</td>
            <td>类型</td>
            <td>备注</td>
            <td>操作</td>
        </tr>
        {foreach $list as $value}
        <tr>
            <td>{$value['securitysn']}</td>
            <td>{$value['title']}</td>
            <td>{$value['comment']}</td>
            <td>
                <a href="/security/edit?id={$value['id']}">修改</a>|
                <a href="/security/del?id={$value['id']}">删除</a>
            </td>
        </tr>
        {/foreach} 
    </table>
</div>
{/block}