{extends file='main_new.phtml'}
{block name=body}
<div id="content">
    <!-- 头图 -->
    <div class="topImg">
        <div class="cont">
            <div class="fl site">
                <h2>沧州液化气站</h2>
                <p>河北沧州</p>
            </div>
            <div class="fr">
                <ul class="clearfix">
                    <li class="first">
                        <p>累计评分<span></span></p>
                        <strong>4.8</strong>
                    </li>
                    <li>
                        <p>累计定气量（kg）</p>
                        <strong>123,873</strong>
                    </li>
                    <li>
                        <p>已使用智能钢瓶</p>
                        <strong>84,987</strong>
                    </li>
                    <li class="last">
                        <p>已有送气工（人）</p>
                        <strong>786</strong>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="w1170">
        <!-- 选择液化气 -->
        <div class="clearfix product">
            <div class="fl imgbox">
                <img src="/statics/newhome/images/img7.png">
            </div>
            <div class="fr cont">
                <div class="clearfix detail">
                    <div class="fl txt">
                        <p class="mb85">选择液化气：</p>
                        <p class="mb20">输入数量：</p>
                        <p>价格：</p>
                    </div>
                    <ul class="fl guige">
                        <li>
                            <strong>150kg</strong>
                            <div class="number">
                                <span class="sub">-</span>
                                <input type="text">
                                <span class="add">+</span>
                            </div>
                            <p>￥112.00</p>
                        </li>
                        <li>
                            <strong>50kg</strong>
                            <div class="number">
                                <span class="sub">-</span>
                                <input type="text">
                                <span class="add">+</span>
                            </div>
                            <p>￥112.00</p>
                        </li>
                        <li class="active">
                            <strong>15kg</strong>
                            <div class="number">
                                <span class="sub">-</span>
                                <input type="text">
                                <span class="add">+</span>
                            </div>
                            <p>￥112.00</p>
                        </li>
                    </ul>
                </div>
                <p class="address">收货人：尤俊珂<span></span>电话：15501287788<span></span>收货地址：河北省沧州市沧县青年路康家沟102号</p>
                <div class="beizhu mb34">
                    订单备注：
                    <input type="text">
                </div>  
                <div class="clearfix">
                    <div class="fl choosetype">
                        <div class="type">
                            <a href="javascript:void(0);">押金用户</a>
                            <a href="javascript:void(0);">紧急用户</a>
                        </div>
                        <div class="checkbox" style="display:none;">
                            <input type="checkbox">押金用户
                            <input type="checkbox">紧急用户	
                        </div>
                    </div>
                    <a href="javascript:void(0);" class="fr blueBtn2 mr10">电话联系</a>
                    <a href="javascript:void(0);" class="fr yellowBtn mr10">添加到订单</a>
                </div>
            </div>
        </div>
        <!-- 优势 -->
        <div class="youshi">
            <ul class="clearfix">
                <li class="clearfix">
                    <div class="pic fl"></div>
                    <div class="fl detail">
                        <h4>智能角阀钢瓶</h4>
                        <p>智能角阀充气枪对智能角阀内嵌芯片信息的识别严格限定定点充装</p>
                    </div>
                </li>
                <li class="clearfix">
                    <div class="pic pic2 fl"></div>
                    <div class="fl detail">
                        <h4>钢瓶档案管理</h4>
                        <p>安检自动提示记录、用户持有钢瓶信息自动记录、出入库自动记录、维修报废自动记录、配送与否自动记录</p>
                    </div>
                </li>
                <li class="clearfix">
                    <div class="pic pic3 fl"></div>
                    <div class="fl detail">
                        <h4>物流自动追踪</h4>
                        <p>正规物流送气工为您送气，可随时查询物流运送位置。</p>
                    </div>
                </li>
            </ul>
        </div>
        <!-- 公司介绍 -->
        <div class="intro clearfix">
            <div class="fl detail">
                <h3>公司介绍</h3>
                <p>北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技使用常识</p>
                <p>北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识京瑞气科技液气安全使用常识京瑞气科化石油气安</p>
            </div>
            <div class="fr picbox">
                <div class="fl imgbox">
                    <img src="/statics/newhome/images/img9.png">
                </div>
                <div class="fl">
                    <div class="imgbox2">
                        <img src="/statics/newhome/images/img10.png">
                    </div>
                    <div class="imgbox3">
                        <img src="/statics/newhome/images/img8.png">
                    </div>
                </div>
            </div>
        </div>
        <!-- 使用常识 -->
        <div class="message clearfix">
            <div class="fl changshi">
                <h4>液化气罐使用常识</h4>
                <p>京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识京</p>
                <p>京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全石油气安全使用常识京</p>
                <p>京瑞气科技液化石油技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识京</p>
            </div>
            <div class="fr pay">
                <h4>注意事项</h4>
                <p>1.京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识京</p>
                <p>2.京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识京</p>
                <p>3.京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识北京瑞气科技液化石油气安全使用常识京</p>
            </div>
        </div>
    </div>
    <!-- 行业动态 安全常识 -->
    {include file='main_new_dynamic.phtml'}
</div>
{/block}