<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0"/>
	<title>评价</title>
	<link rel="stylesheet" href="/statics/css/base.css"/>
	<link rel="stylesheet" href="/statics/css/style.css"/>
	<script src="/statics/js/jquery-1.8.3.min.js"></script>
	<script src="/statics/js/main.js"></script>
	<script type="text/javascript" src="/statics/js/Vue.min.js"></script>
	<script type="text/javascript" src="/statics/js/vue-resource.min.js"></script>
	{include '../header.phtml'}
</head>
<body id="Vbody">
	<div class="goods_detail" style="margin-top: 0">
		<table >
			<tr>
				<td>商品名称</td>
				<td>规格</td>
				<td>单价</td>
				<td>数量</td>
			</tr>
			<template v-for="info in order_info">
				<tr>
					<td>[[info.name]]</td>
					<td>[[info.type]]</td>
					<td>[[info.goods_price]]</td>
					<td>[[info.goods_num]]</td>
				</tr>
			</template>
		</table>
	</div>
	<div class="eval_con">
		<ul class="choose_eval">
			<li><img onclick="Type=1;" class="ch_btn cirle_btn" src="/statics/images/btn_[[type.hp]].png" alt="">好评<img class="flow" src="/statics/images/hao.png" alt=""></li>
			<li><img onclick="Type=2;" class="ch_btn cirle_btn" src="/statics/images/btn_[[type.zp]].png" alt="">中评<img class="flow" src="/statics/images/zhong.png" alt=""></li>
			<li><img onclick="Type=3;" class="ch_btn cirle_btn" src="/statics/images/btn_[[type.cp]].png" alt="">差评<img class="flow" src="/statics/images/cha.png" alt=""></li>
		</ul>
	<template v-if="pl==0">
		
		<div class="eval_text">
			<textarea name="comment" id="comment" placeholder="说说你的想法">[[pl.comment]]</textarea>
		</div>
		<div v-on:click="addComment" class="finish">提交</div>
	</template>
	<template v-else>
		<div class="eval_text">
			<textarea readonly="readonly" name="comment" id="comment" placeholder="说说你的想法">[[pl.comment]]</textarea>
		</div>
	</template>
	</div>
<script type="text/javascript">
var Type = 0;
var ordersn = null;
var type={
		hp:'f',
		zp:'f',
		cp:'f'
	};
new Vue({
	el: '#Vbody',
	ready: function() {
		this.$set('currtime',Date.parse(new Date()));
		this.getOrder();
		this.$set('type',type);
	},
	methods: {
		//获取订单
		getOrder:function(){
			var id = GetQueryString('orderid');
			this.$http.get('/wx/ordermanage/one?id='+id, function(data, status, request) {
				if(data.status==1){
					ordersn = data.data.order_sn;
					this.$set('order_info', data.data.order_info);
					this.getComment();
				}else{
					
				}
				
				//this.redirect(data);
				//console.log(data);
			});
		},
		getComment:function(){
			this.$http.get('/wx/ordermanage/getcomment?ordersn='+ordersn,function(data, status, request){
				if(data.status==1){
					
					switch(data.data.type){
						case '1':
							type.hp='t';
						break;
						case '2':
							type.zp='t';
						break;
						case '3':
							type.cp='t';
						break;
					}
					this.$set('type',type);
					this.$set('pl',data.data);
				}else{
					this.$set('pl',0);
				}
				
			});
		},
		addComment:function(){
			var params = {
				type:Type,
				comment:$("#comment").val(),
				ordersn:ordersn,
			};
			//var ready = this.ready;
			$.ajax({
				  type: 'POST',
				  url: '/wx/ordermanage/addcomment',
				  data: params,
				  cache:false,  
				  dataType:'json',
				  success: function(data){
					  if(data.status==1){
						 //dig("保存成功！");alert
						 dig("评论成功");
						 setTimeout(function(){
						 	location.reload();
						 },1200);
						 
					  }else{
						 dig(data.msg);
					  }
				  },
				  error:function (){
					  //dig('系统繁忙！');
				  }
			});
		}
	}
})
</script>
</body>
</html>