<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0"/>
	<title>评价</title>
	<link rel="stylesheet" href="/statics/css/base.css"/>
	<link rel="stylesheet" href="/statics/css/style.css"/>
	<script src="/statics/js/jquery-1.8.3.min.js"></script>
	<script src="/statics/js/main.js"></script>
	<script type="text/javascript" src="/statics/js/Vue.min.js"></script>
	<script type="text/javascript" src="/statics/js/vue-resource.min.js"></script>
	{include '../header.phtml'}
</head>
<body id="Vbody">
	<div class="goods_detail" style="margin-top: 0">
		<table >
			<tr>
				<td>商品名称</td>
				<td>规格</td>
				<td>单价</td>
				<td>数量</td>
			</tr>
			<template v-for="info in order_info">
				<tr>
					<td>[[info.name]]</td>
					<td>[[info.type]]</td>
					<td>[[info.goods_price]]</td>
					<td>[[info.goods_num]]</td>
				</tr>
			</template>
		</table>
	</div>
	<div class="eval_con">
		<ul class="choose_eval">
			<li><img class="ch_btn cirle_btn" src="/statics/images/btn_f.png" alt="">好评<img class="flow" src="/statics/images/hao.png" alt=""></li>
			<li><img class="ch_btn cirle_btn" src="/statics/images/btn_f.png" alt="">中评<img class="flow" src="/statics/images/zhong.png" alt=""></li>
			<li><img class="ch_btn cirle_btn" src="/statics/images/btn_f.png" alt="">差评<img class="flow" src="/statics/images/cha.png" alt=""></li>
		</ul>
		<div class="eval_text">
			<textarea name="" id="" placeholder="说说你的想法"></textarea>
		</div>
		<div class="finish">提交</div>
		
	</div>
<script type="text/javascript">

new Vue({
	el: '#Vbody',
	ready: function() {
		this.$set('currtime',Date.parse(new Date()));
		this.getOrder();
	},
	methods: {
		//获取订单
		getOrder:function(){
			var id = GetQueryString('orderid');
			this.$http.get('/wx/ordermanage/one?id='+id, function(data, status, request) {
				if(data.status==1){
					this.$set('order_info', data.data.order_info);
				}else{
					
				}
				
				//this.redirect(data);
				//console.log(data);
			});
		},
	}
})
</script>
</body>
</html>