<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0"/>
	<title>订单管理</title>
	<link rel="stylesheet" href="/statics/css/base.css"/>
	<link rel="stylesheet" href="/statics/css/style.css"/>
	<script src="/statics/js/jquery-1.8.3.min.js"></script>
	<script src="/statics/js/main.js"></script>
	<script type="text/javascript" src="/statics/js/Vue.min.js"></script>
	<script type="text/javascript" src="/statics/js/vue-resource.min.js"></script>
	{include '../header.phtml'}
</head>
<body id="Vbody">
	<div class="t_manager">
		<ul>
			<li class="blue_bottom"><span class="r_tip blue_text">全部</span></li>
			<li><span class="r_tip">待收货</span></li>
			<li><span class="r_tip">已完成</span></li>
			<li><span>已评价</span></li>
		</ul>
	</div>
	<!--  全部-->
	<div class="all">
		<div  v-for="order in orders" class="all_detail">
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'" class="all_head">
				<span>订单号：</span>
				<span>[[order.order_sn]]</span>
				<span>[[order.orderstatus]]</span>
			</p>
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span class="st">商品：</span>
				<span class="ell"><template v-for="info in order.order_info">[[info.goods_name]],</template> </span>
			</p>
			<p class="f_border" onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span>金额：</span>
				<span>￥[[order.money]]</span>
				<span class="l_">[[order.order_paytype==1?'网上支付':'现金']]</span>
			</p>
			<div v-if="order.status==4 && order.is_evaluation==0" onclick="location.href='/wx/ordermanage/comment?orderid=[[order.order_id]]'" class="go_eval">去评价</div>
			<div v-if="order.status==4 && order.is_evaluation==1" onclick="location.href='/wx/ordermanage/comment?orderid=[[order.order_id]]'" class="go_eval">已评价</div>
		</div>
		
	</div>
	<!--  待收货-->
	<div class="wait_goods">
		
		<template v-for="order in orders">
		<div  v-if="order.status==2"  class="all_detail go_ps">
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'" class="all_head">
				<span>订单号：</span>
				<span>[[order.order_sn]]</span>
				<span>[[order.orderstatus]]</span>
			</p>
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span class="st">商品：</span>
				<span class="ell">
				<template v-for="info in order.order_info">[[info.goods_name]],</template>
				...
				</span>
			</p>
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span>金额：</span>
				<span>￥[[order.money]]</span>
				<span class="l_">[[order.order_paytype==1?'网上支付':'现金']]</span>
			</p>
		
		</div></template>
		
	</div>
	<!-- 已完成 -->
	<div class="finish_order">
		
		<template v-for="order in orders">
		<div  v-if="order.status==4"  class="all_detail">
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'" class="all_head">
				<span>订单号：</span>
				<span>[[order.order_sn]]</span>
				<span>[[order.orderstatus]]</span>
			</p>
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span class="st">商品：</span>
				<span class="ell"><template v-for="info in order.order_info">[[info.goods_name]],</template>...</span>
			</p>
			<p class="f_border" onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span>金额：</span>
				<span>￥[[order.money]]</span>
				<span class="l_">[[order.order_paytype==1?'网上支付':'现金']]</span>
			</p>
			<div v-if="order.is_evaluation==0" onclick="location.href='/wx/ordermanage/comment?orderid=[[order.order_id]]'" class="go_eval">去评价</div>
			<div v-if="order.is_evaluation==1" onclick="location.href='/wx/ordermanage/comment?orderid=[[order.order_id]]'" class="go_eval">已评价</div>
		
		</div></template>
	</div>
	<!-- 已评价 -->
	<div class="finish_eval">
		
		<template v-for="order in orders">
		<div  v-if="order.is_evaluation==1"  class="all_detail go_detail">
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'" class="all_head">
				<span>订单号：</span>
				<span>[[order.order_sn]]</span>
				<span>[[order.orderstatus]]</span>
			</p>
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span class="st">商品：</span>
				<span class="ell"><template v-for="info in order.order_info">[[info.goods_name]],</template></span>
			</p>
			<p onclick="location.href='/wx/ordermanage/detail?id=[[order.order_id]]'">
				<span>金额：</span>
				<span>￥[[order.money]]</span>
				<span class="l_">[[order.order_paytype==1?'网上支付':'现金']]</span>
			</p>
		</div></template>
	</div>
<script type="text/javascript">
new Vue({
	el: '#Vbody',
	ready: function() {
		this.getOrder();
	},
	methods: {
		//获取订单
		getOrder:function(){
			this.$http.get('/wx/ordermanage/getlist', function(data, status, request) {
				
				if(data.status==1){
					this.$set('orders', data.data);
				}else{
					//alert(123);
				}
				
			});
		},
	}
})
</script>
</body>
</html>