{extends file='ztemp/main.phtml'}
{block name=title}罐装站管理{/block}
{block name=head}
{literal}
<link rel="stylesheet" type="text/css" href="/statics/css/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="/statics/css/ui-dialog.css"/>
<link rel="stylesheet" type="text/css" href="/statics/css/style.css">
<script type="text/javascript" src="/statics/js/require.min.js"></script>
{/literal}
{/block}
{block name=body}
<div class="contRight fr">
    <div class="contRItem">
        <div class="contRTitle">
            罐装站管理
            <span></span>
        </div>
        <div class="contRList">
            <form name="form" method="POST">
                <div class="rqLine clearfix">
                    <div class="rqOption fl">
                        <label class="fl">省/市：</label>
                        <div class="fl areaSelect">
                            <select id="loc_province" name="region_1" style="width:170px;" class="selectmenu region_1"></select>
                        </div>
                    </div>
                    <div class="rqOption fl">
                        <label class="fl">区县：</label>
                        <div class="fl areaSelect">
                            <select id="loc_city" name="region_2" style="width:170px;" class="selectmenu region_2"></select>
                        </div>
                    </div>
                    <div class="rqOption3 fl">
                        <label class="fl">街道：</label>
                        <div class="selectBox fl">
                            <div class="mySelect">
                                <select id="loc_town" name="region_3" style="width:170px;" class="selectmenu region_3"></select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="rqLine clearfix">
                    <div class="rqOption fl">
                        <label class="fl">所属罐装站：</label>
                        <div class="riliInputBox fl">
                            <div class="riliInput fl">
                                <input type="text" name='gas_name' id='username' value="{$param['gas_name']}" style="width:100px;">
                            </div>
                        </div>
                    </div>
                    <div class="rqOption fl">
                        <!--a href='javascript:;' onclick="postPage()" class="blueBtn">搜索</a-->
                        <input type="submit" name="submit" class="blueBtn" value="搜索" />
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="contRItem">
        <div class="contRTitle">
            罐装站列表
            <span></span>
            <a href="/gasstation/add" class="blueBtn6 addStore">添加罐装站</a>
        </div>
        <div class="contRList">
            <div class="rqTabItem">
                <table>
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>站长</th>
                            <th>联系电话</th>
                            <th>座机</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if count($ext['list']) > 0}
                        {foreach $ext['list'] as $value}
                        <tr>
                            <td>{$value['gas_name']}</td>
                            <td>{$value['admin_name']}</td>
                            <td>{$value['mobile_phone']}</td>
                            <td>{$value['tel_phone']}</td>
                            <td><a href="/gasstation/add?id={$value['gas_id']}">修改</a></td>
                        </tr>
                        {/foreach}
                        {else}
                            <tr><td colspan="8">暂时还没有数据</td></tr>
                        {/if}
                    </tbody>
                </table>
            </div>
            <div class="clearfix sqspBottom">
                <p class="fl">共 <span>{$ext['count']}</span> 条记录</p>
                <div class="table-pages pageNav clearfix fr" id="pageNav"></div>
                <input type="hidden" class="currentPage" value="{$page}">
                <input type="hidden" class="totalPage" value="{ceil($ext['count']/15)}">
                <input type="hidden" class="paramlist" value="{$getparamlist}" />
            </div>
        </div>
    </div>
</div>
{/block}
{block name=fjs}<script type="text/javascript" src="/statics/js/controllers/storeManage.js"></script>{/block}