<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
        <meta name="format-detection" content="telephone=no" />
        <link rel="stylesheet" type="text/css" href="/statics/wx/css/layout.css">
        <script type="text/javascript" src="/statics/wx/js/jquery.js"></script>
    </head>
    <body>
        <div class="wrap">
            <div class="menu">
                <ul>
                    <li class="dlLi1">
                        <a href="javascript:;">关注派思微信</a>
                    </li>
                    <li class="dlLi2">
                        <a href="javascript:;">IOS版下载</a>
                    </li>
                    <li class="dlLi3">
                        <a href="javascript:;">Android版下载</a>
                    </li>
                </ul>
            </div>
        </div>

    </body>
</html>